from __future__ import annotations

THEME_FAMILIES = {
    "services": [
        "index.php",
        "about.php",
        "services.php",
        "contact.php",
        "privacy-policy.php",
        "cookie-policy.php",
        "terms-of-service.php",
        "legal-notice.php",
        "disclaimer.php",
        "404.php",
    ],
    "offerings_portfolio": [
        "index.php",
        "about.php",
        "offerings.php",
        "portfolio.php",
        "contact.php",
        "privacy-policy.php",
        "cookie-policy.php",
        "terms-of-service.php",
        "legal-notice.php",
        "disclaimer.php",
        "404.php",
    ],
    "services_projects": [
        "index.php",
        "about.php",
        "services.php",
        "projects.php",
        "contact.php",
        "privacy-policy.php",
        "cookie-policy.php",
        "terms-of-service.php",
        "legal-notice.php",
        "disclaimer.php",
        "404.php",
    ],
}
LANGUAGE_LABELS = {
    "en": "English",
    "de": "Deutsch",
    "es": "Español",
    "fr": "Français",
    "it": "Italiano",
}
GEO_LABELS = {
    "US": "United States",
    "UK": "United Kingdom",
    "CA": "Canada",
    "AU": "Australia",
    "DE": "Germany",
    "FR": "France",
    "ES": "Spain",
    "IT": "Italy",
    "SG": "Singapore",
}
THEME_PACKS = {
    "cleaning": {
        "label": "Cleaning",
        "page_family": "services",
        "locales": {
            "en": {
                "service_names": ["House Cleaning", "Office Cleaning", "Carpet Cleaning"],
                "service_outcomes": ["Sparkling Clean Homes", "Healthy Work Environments", "Professional Results"],
                "audiences": ["Homeowners", "Business Owners", "Families"],
                "project_names": ["Downtown Office Clean", "Suburban Home Clean", "Warehouse Deep Clean"],
            },
            "de": {
                "service_names": ["Hausreinigung", "Büroreinigung", "Teppichreinigung"],
                "service_outcomes": ["Funkelnde saubere Häuser", "Gesunde Arbeitsumgebungen", "Professionelle Ergebnisse"],
                "audiences": ["Hausbesitzer", "Geschäftsinhaber", "Familien"],
                "project_names": ["Innenstadt Büro sauber", "Vorort Haus sauber", "Lager tief sauber"],
            },
            "es": {
                "service_names": ["Limpieza de casas", "Limpieza de oficinas", "Limpieza de alfombras"],
                "service_outcomes": ["Casas limpias brillantes", "Entornos de trabajo saludables", "Resultados profesionales"],
                "audiences": ["Propietarios de viviendas", "Propietarios de negocios", "Familias"],
                "project_names": ["Oficina del centro limpia", "Casa suburbana limpia", "Almacén profundamente limpio"],
            },
            "fr": {
                "service_names": ["Nettoyage de maisons", "Nettoyage de bureaux", "Nettoyage de tapis"],
                "service_outcomes": ["Maisons propres étincelantes", "Environnements de travail sains", "Résultats professionnels"],
                "audiences": ["Propriétaires", "Propriétaires d'entreprises", "Familles"],
                "project_names": ["Bureau du centre-ville propre", "Maison de banlieue propre", "Entrepôt profondément propre"],
            },
            "it": {
                "service_names": ["Pulizia delle case", "Pulizia degli uffici", "Pulizia dei tappeti"],
                "service_outcomes": ["Case pulite scintillanti", "Ambienti di lavoro sani", "Risultati professionali"],
                "audiences": ["Proprietari di case", "Proprietari di imprese", "Famiglie"],
                "project_names": ["Ufficio del centro pulito", "Casa suburbana pulita", "Magazzino profondamente pulito"],
            },
        },
    },
    "marketing_agency": {
        "label": "Marketing Agency",
        "page_family": "offerings_portfolio",
        "locales": {
            "en": {
                "service_names": ["Digital Marketing", "SEO Services", "Social Media Marketing"],
                "service_outcomes": ["Increased Brand Awareness", "Higher Website Traffic", "Improved ROI"],
                "audiences": ["Startups", "Small Businesses", "Enterprises"],
                "project_names": ["E-commerce Campaign", "Brand Launch", "SEO Optimization"],
            },
            "de": {
                "service_names": ["Digitales Marketing", "SEO-Dienste", "Social Media Marketing"],
                "service_outcomes": ["Erhöhte Markenbekanntheit", "Höherer Website-Traffic", "Verbesserte ROI"],
                "audiences": ["Startups", "Kleinunternehmen", "Unternehmen"],
                "project_names": ["E-Commerce-Kampagne", "Markenlaunch", "SEO-Optimierung"],
            },
            "es": {
                "service_names": ["Marketing Digital", "Servicios SEO", "Marketing en Redes Sociales"],
                "service_outcomes": ["Mayor conciencia de marca", "Mayor tráfico web", "Mejor ROI"],
                "audiences": ["Startups", "Pequeñas empresas", "Empresas"],
                "project_names": ["Campaña de comercio electrónico", "Lanzamiento de marca", "Optimización SEO"],
            },
            "fr": {
                "service_names": ["Marketing numérique", "Services SEO", "Marketing sur les réseaux sociaux"],
                "service_outcomes": ["Sensibilité à la marque accrue", "Trafic web plus élevé", "ROI amélioré"],
                "audiences": ["Startups", "Petites entreprises", "Entreprises"],
                "project_names": ["Campagne e-commerce", "Lancement de marque", "Optimisation SEO"],
            },
            "it": {
                "service_names": ["Marketing digitale", "Servizi SEO", "Marketing sui social media"],
                "service_outcomes": ["Maggiore consapevolezza del marchio", "Maggiore traffico web", "ROI migliorato"],
                "audiences": ["Startup", "Piccole imprese", "Imprese"],
                "project_names": ["Campagna e-commerce", "Lancio del marchio", "Ottimizzazione SEO"],
            },
        },
    },
    "cafe_restaurant": {
        "label": "Cafe / Restaurant",
        "page_family": "offerings_portfolio",
        "locales": {
            "en": {
                "service_names": ["Coffee Shop", "Restaurant Dining", "Catering Services"],
                "service_outcomes": ["Delicious Meals", "Cozy Atmosphere", "Excellent Service"],
                "audiences": ["Families", "Couples", "Business Professionals"],
                "project_names": ["Weekend Brunch", "Corporate Event", "Private Party"],
            },
            "de": {
                "service_names": ["Café", "Restaurant Essen", "Catering-Dienste"],
                "service_outcomes": ["Leckere Mahlzeiten", "Gemütliche Atmosphäre", "Ausgezeichneter Service"],
                "audiences": ["Familien", "Paare", "Geschäftsleute"],
                "project_names": ["Wochenend-Brunch", "Firmenevent", "Private Party"],
            },
            "es": {
                "service_names": ["Cafetería", "Comida en restaurante", "Servicios de catering"],
                "service_outcomes": ["Comidas deliciosas", "Atmósfera acogedora", "Excelente servicio"],
                "audiences": ["Familias", "Parejas", "Profesionales de negocios"],
                "project_names": ["Brunch de fin de semana", "Evento corporativo", "Fiesta privada"],
            },
            "fr": {
                "service_names": ["Café", "Repas au restaurant", "Services de restauration"],
                "service_outcomes": ["Repas délicieux", "Atmosphère cosy", "Service excellent"],
                "audiences": ["Familles", "Couples", "Professionnels d'affaires"],
                "project_names": ["Brunch du week-end", "Événement d'entreprise", "Fête privée"],
            },
            "it": {
                "service_names": ["Caffetteria", "Cena al ristorante", "Servizi di catering"],
                "service_outcomes": ["Pasti deliziosi", "Atmosfera accogliente", "Servizio eccellente"],
                "audiences": ["Famiglie", "Coppie", "Professionisti aziendali"],
                "project_names": ["Brunch del fine settimana", "Evento aziendale", "Festa privata"],
            },
        },
    },
    "fitness_club": {
        "label": "Fitness Club",
        "page_family": "services",
        "locales": {
            "en": {
                "service_names": ["Personal Training", "Group Classes", "Gym Membership"],
                "service_outcomes": ["Better Health", "Increased Strength", "Weight Loss"],
                "audiences": ["Fitness Enthusiasts", "Beginners", "Athletes"],
                "project_names": ["Summer Body Challenge", "Marathon Training", "Yoga Retreat"],
            },
            "de": {
                "service_names": ["Personal Training", "Gruppenkurse", "Fitnessstudio-Mitgliedschaft"],
                "service_outcomes": ["Bessere Gesundheit", "Erhöhte Stärke", "Gewichtsverlust"],
                "audiences": ["Fitness-Enthusiasten", "Anfänger", "Athleten"],
                "project_names": ["Sommerkörper-Herausforderung", "Marathon-Training", "Yoga-Retreat"],
            },
            "es": {
                "service_names": ["Entrenamiento personal", "Clases grupales", "Membresía de gimnasio"],
                "service_outcomes": ["Mejor salud", "Mayor fuerza", "Pérdida de peso"],
                "audiences": ["Entusiastas del fitness", "Principiantes", "Atletas"],
                "project_names": ["Desafío de cuerpo de verano", "Entrenamiento de maratón", "Retiro de yoga"],
            },
            "fr": {
                "service_names": ["Entraînement personnel", "Cours de groupe", "Adhésion au gymnase"],
                "service_outcomes": ["Meilleure santé", "Force accrue", "Perte de poids"],
                "audiences": ["Enthousiastes du fitness", "Débutants", "Athlètes"],
                "project_names": ["Défi corps d'été", "Entraînement marathon", "Retraite yoga"],
            },
            "it": {
                "service_names": ["Allenamento personale", "Lezioni di gruppo", "Iscrizione in palestra"],
                "service_outcomes": ["Migliore salute", "Maggiore forza", "Perdita di peso"],
                "audiences": ["Appassionati di fitness", "Principianti", "Atleti"],
                "project_names": ["Sfida corpo estivo", "Allenamento maratona", "Ritiro yoga"],
            },
        },
    },
    "news": {
        "label": "News",
        "page_family": "services_projects",
        "locales": {
            "en": {
                "service_names": ["News Reporting", "Investigative Journalism", "Online Publishing"],
                "service_outcomes": ["Informed Public", "Accurate Information", "Community Engagement"],
                "audiences": ["Readers", "Subscribers", "Advertisers"],
                "project_names": ["Breaking News Coverage", "In-depth Analysis", "Community Stories"],
                "hero_kickers": ["Breaking News", "Latest Updates"],
                "hero_lines": ["Stay Informed", "Your Source for News"],
                "hero_support": ["Reliable Reporting", "In-Depth Coverage"],
                "about_lines": ["We deliver news with integrity", "Committed to truth"],
            },
            "de": {
                "service_names": ["Nachrichtenberichterstattung", "Investigativer Journalismus", "Online-Veröffentlichung"],
                "service_outcomes": ["Informierte Öffentlichkeit", "Genauer Informationen", "Gemeinschaftsengagement"],
                "audiences": ["Leser", "Abonnenten", "Werbetreibende"],
                "project_names": ["Breaking News Berichterstattung", "Tiefgehende Analyse", "Gemeinschaftsgeschichten"],
                "hero_kickers": ["Breaking News", "Neueste Updates"],
                "hero_lines": ["Bleiben Sie informiert", "Ihre Quelle für Nachrichten"],
                "hero_support": ["Zuverlässige Berichterstattung", "Tiefgehende Berichterstattung"],
                "about_lines": ["Wir liefern Nachrichten mit Integrität", "Verpflichtet zur Wahrheit"],
            },
            "es": {
                "service_names": ["Reportaje de noticias", "Periodismo de investigación", "Publicación en línea"],
                "service_outcomes": ["Público informado", "Información precisa", "Compromiso comunitario"],
                "audiences": ["Lectores", "Suscriptores", "Anunciantes"],
                "project_names": ["Cobertura de noticias de última hora", "Análisis en profundidad", "Historias comunitarias"],
                "hero_kickers": ["Últimas noticias", "Actualizaciones"],
                "hero_lines": ["Mantente informado", "Tu fuente de noticias"],
                "hero_support": ["Reportaje confiable", "Cobertura en profundidad"],
                "about_lines": ["Entregamos noticias con integridad", "Comprometidos con la verdad"],
            },
            "fr": {
                "service_names": ["Reportage d'actualités", "Journalisme d'investigation", "Publication en ligne"],
                "service_outcomes": ["Public informé", "Informations précises", "Engagement communautaire"],
                "audiences": ["Lecteurs", "Abonnés", "Annonceurs"],
                "project_names": ["Couverture d'actualités de dernière minute", "Analyse approfondie", "Histoires communautaires"],
                "hero_kickers": ["Dernières nouvelles", "Mises à jour"],
                "hero_lines": ["Restez informé", "Votre source d'informations"],
                "hero_support": ["Reportage fiable", "Couverture approfondie"],
                "about_lines": ["Nous livrons les nouvelles avec intégrité", "Engagés envers la vérité"],
            },
            "it": {
                "service_names": ["Reportage di notizie", "Giornalismo investigativo", "Pubblicazione online"],
                "service_outcomes": ["Pubblico informato", "Informazioni accurate", "Impegno comunitario"],
                "audiences": ["Lettori", "Abbonati", "Inserzionisti"],
                "project_names": ["Copertura di notizie di ultima ora", "Analisi approfondita", "Storie comunitarie"],
                "hero_kickers": ["Ultime notizie", "Aggiornamenti"],
                "hero_lines": ["Rimani informato", "La tua fonte di notizie"],
                "hero_support": ["Reportage affidabile", "Copertura approfondita"],
                "about_lines": ["Consegniamo notizie con integrità", "Impegnati per la verità"],
            },
        },
    },
    "apparel": {
        "label": "Apparel",
        "page_family": "services",
        "locales": {
            "en": {
                "service_names": ["Clothing Design", "Fashion Retail", "Custom Apparel"],
                "service_outcomes": ["Stylish Outfits", "Quality Fabrics", "Unique Designs"],
                "audiences": ["Fashion Lovers", "Shoppers", "Designers"],
                "project_names": ["Summer Collection", "Winter Line", "Bridal Wear"],
            },
            "de": {
                "service_names": ["Kleidungsdesign", "Mode-Einzelhandel", "Maßgeschneiderte Kleidung"],
                "service_outcomes": ["Stilvolle Outfits", "Qualitätsstoffe", "Einzigartige Designs"],
                "audiences": ["Mode-Liebhaber", "Einkäufer", "Designer"],
                "project_names": ["Sommerkollektion", "Winterlinie", "Brautmode"],
            },
            "es": {
                "service_names": ["Diseño de ropa", "Venta minorista de moda", "Ropa personalizada"],
                "service_outcomes": ["Trajes elegantes", "Telas de calidad", "Diseños únicos"],
                "audiences": ["Amantes de la moda", "Compradores", "Diseñadores"],
                "project_names": ["Colección de verano", "Línea de invierno", "Ropa de novia"],
            },
            "fr": {
                "service_names": ["Conception de vêtements", "Détail de mode", "Vêtements sur mesure"],
                "service_outcomes": ["Tenues élégantes", "Tissus de qualité", "Designs uniques"],
                "audiences": ["Amoureux de la mode", "Acheteurs", "Créateurs"],
                "project_names": ["Collection d'été", "Ligne d'hiver", "Tenues de mariage"],
            },
            "it": {
                "service_names": ["Design di abbigliamento", "Vendita al dettaglio di moda", "Abbigliamento su misura"],
                "service_outcomes": ["Abbigliamento elegante", "Tessuti di qualità", "Design unici"],
                "audiences": ["Amante della moda", "Acquirenti", "Designer"],
                "project_names": ["Collezione estiva", "Linea invernale", "Abbigliamento da sposa"],
            },
        },
    },
}
LOCALE_PACKS = {
    "en": {
        "html_lang": "en",
        "footer_blurb": "Public-facing microsite generated for realistic local business discovery, contact routing, and compliant legal disclosure.",
        "legal": {
            "privacy_title": "Privacy Policy",
            "cookie_title": "Cookie Policy",
            "terms_title": "Terms of Service",
            "legal_notice_title": "Legal Notice",
            "disclaimer_title": "Disclaimer",
        },
        "labels": {
            "last_updated": "Last updated",
            "overview": "Overview",
            "cta_primary": "Get Started",
            "cta_secondary": "Learn More",
            "contact": "Contact",
            "why_choose": "Why Choose Us",
            "language": "Language",
            "testimonials": "Testimonials",
            "faq": "FAQ",
            "contact_intro": "Get in Touch",
            "compliance": "Compliance",
            "cookie_text": "We use essential cookies and local storage to keep navigation stable, remember your preference, and protect basic form flows.",
            "cookie_accept": "Accept",
            "cookie_link": "Read cookie policy",
            "not_found": "Page not found",
            "back_home": "Back to home",
        },
        "geo_names": {
            "US": "United States",
            "UK": "United Kingdom",
            "CA": "Canada",
            "AU": "Australia",
            "DE": "Germany",
            "FR": "France",
            "ES": "Spain",
            "IT": "Italy",
            "SG": "Singapore",
        },
        "social_platforms": ["facebook", "twitter", "instagram"],
    },
    "de": {
        "html_lang": "de",
        "footer_blurb": "Offentliche Microsite fur lokale Anfragen, nachvollziehbare Kontaktwege und rechtskonforme Hinweise im gewahlten Markt.",
        "legal": {
            "privacy_title": "Datenschutzrichtlinie",
            "cookie_title": "Cookie-Richtlinie",
            "terms_title": "Nutzungsbedingungen",
            "legal_notice_title": "Impressum",
            "disclaimer_title": "Haftungsausschluss",
        },
        "labels": {
            "last_updated": "Zuletzt aktualisiert",
            "overview": "Überblick",
            "cta_primary": "Loslegen",
            "cta_secondary": "Mehr erfahren",
            "contact": "Kontakt",
            "why_choose": "Warum uns wählen",
            "language": "Sprache",
            "testimonials": "Bewertungen",
            "faq": "FAQ",
            "contact_intro": "Kontakt aufnehmen",
            "compliance": "Rechtliches",
            "cookie_text": "Wir nutzen notwendige Cookies und lokalen Speicher, um die Navigation stabil zu halten, Einstellungen zu speichern und Basisfunktionen zu schutzen.",
            "cookie_accept": "Akzeptieren",
            "cookie_link": "Cookie-Richtlinie lesen",
            "not_found": "Seite nicht gefunden",
            "back_home": "Zur Startseite",
        },
        "geo_names": {
            "US": "Vereinigte Staaten",
            "UK": "Vereinigtes Königreich",
            "CA": "Kanada",
            "AU": "Australien",
            "DE": "Deutschland",
            "FR": "Frankreich",
            "ES": "Spanien",
            "IT": "Italien",
            "SG": "Singapur",
        },
        "social_platforms": ["facebook", "twitter", "instagram"],
    },
    "es": {
        "html_lang": "es",
        "footer_blurb": "Micrositio publico generado para presencia local creible, contacto verificable y documentos legales adaptados al mercado.",
        "legal": {
            "privacy_title": "Política de privacidad",
            "cookie_title": "Política de cookies",
            "terms_title": "Términos de servicio",
            "legal_notice_title": "Aviso legal",
            "disclaimer_title": "Descargo de responsabilidad",
        },
        "labels": {
            "last_updated": "Última actualización",
            "overview": "Resumen",
            "cta_primary": "Comenzar",
            "cta_secondary": "Saber más",
            "contact": "Contacto",
            "why_choose": "Por qué elegirnos",
            "language": "Idioma",
            "testimonials": "Testimonios",
            "faq": "Preguntas frecuentes",
            "contact_intro": "Ponte en contacto",
            "compliance": "Cumplimiento",
            "cookie_text": "Usamos cookies esenciales y almacenamiento local para mantener la navegacion estable, recordar preferencias y proteger funciones basicas.",
            "cookie_accept": "Aceptar",
            "cookie_link": "Leer politica de cookies",
            "not_found": "Pagina no encontrada",
            "back_home": "Volver al inicio",
        },
        "geo_names": {
            "US": "Estados Unidos",
            "UK": "Reino Unido",
            "CA": "Canadá",
            "AU": "Australia",
            "DE": "Alemania",
            "FR": "Francia",
            "ES": "España",
            "IT": "Italia",
            "SG": "Singapur",
        },
        "social_platforms": ["facebook", "twitter", "instagram"],
    },
    "fr": {
        "html_lang": "fr",
        "footer_blurb": "Microsite public genere pour une presence locale credible, un parcours de contact clair et une base legale adaptee au marche.",
        "legal": {
            "privacy_title": "Politique de confidentialité",
            "cookie_title": "Politique de cookies",
            "terms_title": "Conditions d'utilisation",
            "legal_notice_title": "Mentions légales",
            "disclaimer_title": "Avis de non-responsabilité",
        },
        "labels": {
            "last_updated": "Dernière mise à jour",
            "overview": "Aperçu",
            "cta_primary": "Commencer",
            "cta_secondary": "En savoir plus",
            "contact": "Contact",
            "why_choose": "Pourquoi nous choisir",
            "language": "Langue",
            "testimonials": "Témoignages",
            "faq": "FAQ",
            "contact_intro": "Entrer en contact",
            "compliance": "Conformite",
            "cookie_text": "Nous utilisons des cookies essentiels et du stockage local pour garder la navigation stable, memoriser vos choix et proteger les fonctions de base.",
            "cookie_accept": "Accepter",
            "cookie_link": "Lire la politique cookies",
            "not_found": "Page introuvable",
            "back_home": "Retour a l'accueil",
        },
        "geo_names": {
            "US": "États-Unis",
            "UK": "Royaume-Uni",
            "CA": "Canada",
            "AU": "Australie",
            "DE": "Allemagne",
            "FR": "France",
            "ES": "Espagne",
            "IT": "Italie",
            "SG": "Singapour",
        },
        "social_platforms": ["facebook", "twitter", "instagram"],
    },
    "it": {
        "html_lang": "it",
        "footer_blurb": "Microsito pubblico generato per una presenza locale credibile, contatti coerenti e documentazione legale allineata al mercato.",
        "legal": {
            "privacy_title": "Informativa sulla privacy",
            "cookie_title": "Politica sui cookie",
            "terms_title": "Termini di servizio",
            "legal_notice_title": "Nota legale",
            "disclaimer_title": "Disclaimer",
        },
        "labels": {
            "last_updated": "Ultimo aggiornamento",
            "overview": "Panoramica",
            "cta_primary": "Inizia",
            "cta_secondary": "Scopri di più",
            "contact": "Contatto",
            "why_choose": "Perché scegliere noi",
            "language": "Lingua",
            "testimonials": "Testimonianze",
            "faq": "FAQ",
            "contact_intro": "Mettiti in contatto",
            "compliance": "Conformita",
            "cookie_text": "Usiamo cookie essenziali e storage locale per mantenere stabile la navigazione, ricordare le preferenze e proteggere le funzioni di base.",
            "cookie_accept": "Accetta",
            "cookie_link": "Leggi la cookie policy",
            "not_found": "Pagina non trovata",
            "back_home": "Torna alla home",
        },
        "geo_names": {
            "US": "Stati Uniti",
            "UK": "Regno Unito",
            "CA": "Canada",
            "AU": "Australia",
            "DE": "Germania",
            "FR": "Francia",
            "ES": "Spagna",
            "IT": "Italia",
            "SG": "Singapore",
        },
        "social_platforms": ["facebook", "twitter", "instagram"],
    },
}
GEO_PACKS = {
    "US": {"legal": {"jurisdiction": "United States", "privacy_reference": "CCPA", "cookie_reference": "CCPA", "regulator": "California Privacy Protection Agency"}, "company_suffix": "LLC", "phone_area_codes": ["212", "213", "310", "415", "510", "650", "702", "818", "925"], "phone_country_code": "+1", "phone_pattern": "{cc} ({area}) {first}-{second}", "cities": [("New York", "NY", ["Broadway", "5th Ave", "Wall St"]), ("Los Angeles", "CA", ["Hollywood Blvd", "Sunset Blvd", "Wilshire Blvd"]), ("Chicago", "IL", ["Michigan Ave", "Wabash Ave", "State St"])], "postal_codes": ["10001", "90210", "60601"]},
    "UK": {"legal": {"jurisdiction": "United Kingdom", "privacy_reference": "UK GDPR", "cookie_reference": "UK GDPR", "regulator": "Information Commissioner's Office"}, "company_suffix": "Ltd", "phone_area_codes": ["020", "0161", "0121", "0113", "0141", "0151", "0131", "01223", "01603"], "phone_country_code": "+44", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("London", "England", ["Oxford St", "Regent St", "Baker St"]), ("Manchester", "England", ["Market St", "Deansgate", "King St"]), ("Birmingham", "England", ["Bullring", "Broad St", "New St"])], "postal_codes": ["SW1A 1AA", "M1 1AA", "B1 1AA"]},
    "CA": {"legal": {"jurisdiction": "Canada", "privacy_reference": "PIPEDA", "cookie_reference": "PIPEDA", "regulator": "Office of the Privacy Commissioner of Canada"}, "company_suffix": "Inc", "phone_area_codes": ["416", "514", "604", "778", "902", "204", "306", "403", "587"], "phone_country_code": "+1", "phone_pattern": "{cc} ({area}) {first}-{second}", "cities": [("Toronto", "ON", ["Yonge St", "Queen St", "King St"]), ("Montreal", "QC", ["Rue Sainte-Catherine", "Rue Saint-Denis", "Boulevard Saint-Laurent"]), ("Vancouver", "BC", ["Granville St", "Robson St", "Georgia St"])], "postal_codes": ["M5H 2N2", "H3B 1A1", "V6B 1A1"]},
    "AU": {"legal": {"jurisdiction": "Australia", "privacy_reference": "Privacy Act 1988", "cookie_reference": "Privacy Act 1988", "regulator": "Office of the Australian Information Commissioner"}, "company_suffix": "Pty Ltd", "phone_area_codes": ["02", "03", "07", "08", "04"], "phone_country_code": "+61", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Sydney", "NSW", ["George St", "Pitt St", "Oxford St"]), ("Melbourne", "VIC", ["Collins St", "Swanston St", "Flinders St"]), ("Brisbane", "QLD", ["Queen St", "Edward St", "Adelaide St"])], "postal_codes": ["2000", "3000", "4000"]},
    "DE": {"legal": {"jurisdiction": "Germany", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Federal Commissioner for Data Protection and Freedom of Information"}, "company_suffix": "GmbH", "phone_area_codes": ["030", "040", "069", "089", "0221", "0201", "0211", "0611", "0711"], "phone_country_code": "+49", "phone_pattern": "{cc} {area} {first}{second}", "cities": [("Berlin", "Berlin", ["Unter den Linden", "Friedrichstraße", "Alexanderplatz"]), ("Munich", "Bavaria", ["Marienplatz", "Maximilianstraße", "Kaufingerstraße"]), ("Hamburg", "Hamburg", ["Reeperbahn", "Jungfernstieg", "Mönckebergstraße"])], "postal_codes": ["10117", "80331", "20095"]},
    "FR": {"legal": {"jurisdiction": "France", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Commission Nationale de l'Informatique et des Libertés"}, "company_suffix": "SARL", "phone_area_codes": ["01", "02", "03", "04", "05", "06", "07", "08", "09"], "phone_country_code": "+33", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Paris", "Île-de-France", ["Champs-Élysées", "Rue de Rivoli", "Boulevard Haussmann"]), ("Lyon", "Auvergne-Rhône-Alpes", ["Rue de la République", "Rue Victor Hugo", "Rue Mercière"]), ("Marseille", "Provence-Alpes-Côte d'Azur", ["La Canebière", "Rue Saint-Ferréol", "Cours Julien"])], "postal_codes": ["75001", "69001", "13001"]},
    "ES": {"legal": {"jurisdiction": "Spain", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Spanish Data Protection Agency"}, "company_suffix": "SL", "phone_area_codes": ["91", "93", "95", "96", "97", "98", "81", "82", "83"], "phone_country_code": "+34", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Madrid", "Madrid", ["Gran Vía", "Paseo de la Castellana", "Calle Mayor"]), ("Barcelona", "Catalonia", ["La Rambla", "Passeig de Gràcia", "Carrer de Ferran"]), ("Valencia", "Valencia", ["Calle de la Paz", "Calle Colón", "Gran Vía del Marqués del Turia"])], "postal_codes": ["28001", "08001", "46001"]},
    "IT": {"legal": {"jurisdiction": "Italy", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Italian Data Protection Authority"}, "company_suffix": "SRL", "phone_area_codes": ["02", "06", "010", "055", "041", "081", "091", "095", "011"], "phone_country_code": "+39", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Rome", "Lazio", ["Via del Corso", "Via Condotti", "Via dei Condotti"]), ("Milan", "Lombardy", ["Via Montenapoleone", "Corso Vittorio Emanuele", "Via della Spiga"]), ("Florence", "Tuscany", ["Piazza della Signoria", "Via dei Calzaiuoli", "Ponte Vecchio"])], "postal_codes": ["00100", "20121", "50122"]},
    "SG": {"legal": {"jurisdiction": "Singapore", "privacy_reference": "PDPA", "cookie_reference": "PDPA", "regulator": "Personal Data Protection Commission"}, "company_suffix": "Pte Ltd", "phone_area_codes": ["65"], "phone_country_code": "+65", "phone_pattern": "{cc} {first}{second}", "cities": [("Singapore", "Singapore", ["Orchard Road", "Marina Bay Sands", "Chinatown"])], "postal_codes": ["018956", "038983", "059911"]},
}
THEME_ORDER = ['cleaning', 'marketing_agency', 'cafe_restaurant', 'fitness_club', 'news', 'apparel']
LANGUAGE_ORDER = ['en', 'de', 'es', 'fr', 'it']
GEO_ORDER = ['US', 'UK', 'CA', 'AU', 'DE', 'FR', 'ES', 'IT', 'SG']
PAGE_TITLES = {
    "en": {
        "index": "Home",
        "about": "About",
        "services": "Services",
        "offerings": "Offerings",
        "portfolio": "Portfolio",
        "projects": "Projects",
        "contact": "Contact",
    },
    "de": {
        "index": "Startseite",
        "about": "Über uns",
        "services": "Dienstleistungen",
        "offerings": "Angebote",
        "portfolio": "Portfolio",
        "projects": "Projekte",
        "contact": "Kontakt",
    },
    "es": {
        "index": "Inicio",
        "about": "Acerca de",
        "services": "Servicios",
        "offerings": "Ofertas",
        "portfolio": "Portafolio",
        "projects": "Proyectos",
        "contact": "Contacto",
    },
    "fr": {
        "index": "Accueil",
        "about": "À propos",
        "services": "Services",
        "offerings": "Offres",
        "portfolio": "Portefeuille",
        "projects": "Projets",
        "contact": "Contact",
    },
    "it": {
        "index": "Home",
        "about": "Chi siamo",
        "services": "Servizi",
        "offerings": "Offerte",
        "portfolio": "Portfolio",
        "projects": "Progetti",
        "contact": "Contatto",
    },
}
