from __future__ import annotations

THEME_FAMILIES = {
    "services": [
        "index.php",
        "about.php",
        "services.php",
        "contact.php",
        "privacy-policy.php",
        "cookie-policy.php",
        "terms-of-service.php",
        "legal-notice.php",
        "disclaimer.php",
        "404.php",
    ],
    "offerings_portfolio": [
        "index.php",
        "about.php",
        "offerings.php",
        "portfolio.php",
        "contact.php",
        "privacy-policy.php",
        "cookie-policy.php",
        "terms-of-service.php",
        "legal-notice.php",
        "disclaimer.php",
        "404.php",
    ],
    "services_projects": [
        "index.php",
        "about.php",
        "services.php",
        "projects.php",
        "contact.php",
        "privacy-policy.php",
        "cookie-policy.php",
        "terms-of-service.php",
        "legal-notice.php",
        "disclaimer.php",
        "404.php",
    ],
}
LANGUAGE_LABELS = {
    "en": "English",
    "de": "Deutsch",
    "es": "Español",
    "fr": "Français",
    "it": "Italiano",
}
GEO_LABELS = {
    # North America
    "US": "United States",
    "CA": "Canada",
    "MX": "Mexico",
    # Europe
    "UK": "United Kingdom",
    "DE": "Germany",
    "FR": "France",
    "ES": "Spain",
    "IT": "Italy",
    "AT": "Austria",
    "BE": "Belgium",
    "BG": "Bulgaria",
    "CH": "Switzerland",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "EE": "Estonia",
    "FI": "Finland",
    "GR": "Greece",
    "HR": "Croatia",
    "HU": "Hungary",
    "IE": "Ireland",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "MT": "Malta",
    "NL": "Netherlands",
    "NO": "Norway",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "SE": "Sweden",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "UA": "Ukraine",
    # Asia
    "SG": "Singapore",
    "JP": "Japan",
    "CN": "China",
    "KR": "South Korea",
    "IN": "India",
    "TH": "Thailand",
    "ID": "Indonesia",
    "MY": "Malaysia",
    "PH": "Philippines",
    "VN": "Vietnam",
    "TW": "Taiwan",
    "HK": "Hong Kong",
    "AE": "United Arab Emirates",
    "SA": "Saudi Arabia",
    "IL": "Israel",
    "TR": "Turkey",
    "BD": "Bangladesh",
    "KH": "Cambodia",
    # Oceania
    "AU": "Australia",
    "NZ": "New Zealand",
    # Latin America
    "BR": "Brazil",
    "AR": "Argentina",
    "CO": "Colombia",
    "CL": "Chile",
    "PE": "Peru",
    "VE": "Venezuela",
    "EC": "Ecuador",
    "BO": "Bolivia",
    "PY": "Paraguay",
    "UY": "Uruguay",
    "CR": "Costa Rica",
    "PA": "Panama",
    "GT": "Guatemala",
    "DO": "Dominican Republic",
}
THEME_PACKS = {
    "cleaning": {
        "label": "Cleaning",
        "page_family": "services",
        "locales": {
            "en": {
                "service_names": ["House Cleaning", "Office Cleaning", "Carpet Cleaning"],
                "service_outcomes": ["Sparkling Clean Homes", "Healthy Work Environments", "Professional Results"],
                "audiences": ["Homeowners", "Business Owners", "Families"],
                "project_names": ["Downtown Office Clean", "Suburban Home Clean", "Warehouse Deep Clean"],
            },
            "de": {
                "service_names": ["Hausreinigung", "Büroreinigung", "Teppichreinigung"],
                "service_outcomes": ["Funkelnde saubere Häuser", "Gesunde Arbeitsumgebungen", "Professionelle Ergebnisse"],
                "audiences": ["Hausbesitzer", "Geschäftsinhaber", "Familien"],
                "project_names": ["Innenstadt Büro sauber", "Vorort Haus sauber", "Lager tief sauber"],
            },
            "es": {
                "service_names": ["Limpieza de casas", "Limpieza de oficinas", "Limpieza de alfombras"],
                "service_outcomes": ["Casas limpias brillantes", "Entornos de trabajo saludables", "Resultados profesionales"],
                "audiences": ["Propietarios de viviendas", "Propietarios de negocios", "Familias"],
                "project_names": ["Oficina del centro limpia", "Casa suburbana limpia", "Almacén profundamente limpio"],
            },
            "fr": {
                "service_names": ["Nettoyage de maisons", "Nettoyage de bureaux", "Nettoyage de tapis"],
                "service_outcomes": ["Maisons propres étincelantes", "Environnements de travail sains", "Résultats professionnels"],
                "audiences": ["Propriétaires", "Propriétaires d'entreprises", "Familles"],
                "project_names": ["Bureau du centre-ville propre", "Maison de banlieue propre", "Entrepôt profondément propre"],
            },
            "it": {
                "service_names": ["Pulizia delle case", "Pulizia degli uffici", "Pulizia dei tappeti"],
                "service_outcomes": ["Case pulite scintillanti", "Ambienti di lavoro sani", "Risultati professionali"],
                "audiences": ["Proprietari di case", "Proprietari di imprese", "Famiglie"],
                "project_names": ["Ufficio del centro pulito", "Casa suburbana pulita", "Magazzino profondamente pulito"],
            },
        },
    },
    "marketing_agency": {
        "label": "Marketing Agency",
        "page_family": "offerings_portfolio",
        "locales": {
            "en": {
                "service_names": ["Digital Marketing", "SEO Services", "Social Media Marketing"],
                "service_outcomes": ["Increased Brand Awareness", "Higher Website Traffic", "Improved ROI"],
                "audiences": ["Startups", "Small Businesses", "Enterprises"],
                "project_names": ["E-commerce Campaign", "Brand Launch", "SEO Optimization"],
            },
            "de": {
                "service_names": ["Digitales Marketing", "SEO-Dienste", "Social Media Marketing"],
                "service_outcomes": ["Erhöhte Markenbekanntheit", "Höherer Website-Traffic", "Verbesserte ROI"],
                "audiences": ["Startups", "Kleinunternehmen", "Unternehmen"],
                "project_names": ["E-Commerce-Kampagne", "Markenlaunch", "SEO-Optimierung"],
            },
            "es": {
                "service_names": ["Marketing Digital", "Servicios SEO", "Marketing en Redes Sociales"],
                "service_outcomes": ["Mayor conciencia de marca", "Mayor tráfico web", "Mejor ROI"],
                "audiences": ["Startups", "Pequeñas empresas", "Empresas"],
                "project_names": ["Campaña de comercio electrónico", "Lanzamiento de marca", "Optimización SEO"],
            },
            "fr": {
                "service_names": ["Marketing numérique", "Services SEO", "Marketing sur les réseaux sociaux"],
                "service_outcomes": ["Sensibilité à la marque accrue", "Trafic web plus élevé", "ROI amélioré"],
                "audiences": ["Startups", "Petites entreprises", "Entreprises"],
                "project_names": ["Campagne e-commerce", "Lancement de marque", "Optimisation SEO"],
            },
            "it": {
                "service_names": ["Marketing digitale", "Servizi SEO", "Marketing sui social media"],
                "service_outcomes": ["Maggiore consapevolezza del marchio", "Maggiore traffico web", "ROI migliorato"],
                "audiences": ["Startup", "Piccole imprese", "Imprese"],
                "project_names": ["Campagna e-commerce", "Lancio del marchio", "Ottimizzazione SEO"],
            },
        },
    },
    "cafe_restaurant": {
        "label": "Cafe / Restaurant",
        "page_family": "offerings_portfolio",
        "locales": {
            "en": {
                "service_names": ["Coffee Shop", "Restaurant Dining", "Catering Services"],
                "service_outcomes": ["Delicious Meals", "Cozy Atmosphere", "Excellent Service"],
                "audiences": ["Families", "Couples", "Business Professionals"],
                "project_names": ["Weekend Brunch", "Corporate Event", "Private Party"],
            },
            "de": {
                "service_names": ["Café", "Restaurant Essen", "Catering-Dienste"],
                "service_outcomes": ["Leckere Mahlzeiten", "Gemütliche Atmosphäre", "Ausgezeichneter Service"],
                "audiences": ["Familien", "Paare", "Geschäftsleute"],
                "project_names": ["Wochenend-Brunch", "Firmenevent", "Private Party"],
            },
            "es": {
                "service_names": ["Cafetería", "Comida en restaurante", "Servicios de catering"],
                "service_outcomes": ["Comidas deliciosas", "Atmósfera acogedora", "Excelente servicio"],
                "audiences": ["Familias", "Parejas", "Profesionales de negocios"],
                "project_names": ["Brunch de fin de semana", "Evento corporativo", "Fiesta privada"],
            },
            "fr": {
                "service_names": ["Café", "Repas au restaurant", "Services de restauration"],
                "service_outcomes": ["Repas délicieux", "Atmosphère cosy", "Service excellent"],
                "audiences": ["Familles", "Couples", "Professionnels d'affaires"],
                "project_names": ["Brunch du week-end", "Événement d'entreprise", "Fête privée"],
            },
            "it": {
                "service_names": ["Caffetteria", "Cena al ristorante", "Servizi di catering"],
                "service_outcomes": ["Pasti deliziosi", "Atmosfera accogliente", "Servizio eccellente"],
                "audiences": ["Famiglie", "Coppie", "Professionisti aziendali"],
                "project_names": ["Brunch del fine settimana", "Evento aziendale", "Festa privata"],
            },
        },
    },
    "fitness_club": {
        "label": "Fitness Club",
        "page_family": "services",
        "locales": {
            "en": {
                "service_names": ["Personal Training", "Group Classes", "Gym Membership"],
                "service_outcomes": ["Better Health", "Increased Strength", "Weight Loss"],
                "audiences": ["Fitness Enthusiasts", "Beginners", "Athletes"],
                "project_names": ["Summer Body Challenge", "Marathon Training", "Yoga Retreat"],
            },
            "de": {
                "service_names": ["Personal Training", "Gruppenkurse", "Fitnessstudio-Mitgliedschaft"],
                "service_outcomes": ["Bessere Gesundheit", "Erhöhte Stärke", "Gewichtsverlust"],
                "audiences": ["Fitness-Enthusiasten", "Anfänger", "Athleten"],
                "project_names": ["Sommerkörper-Herausforderung", "Marathon-Training", "Yoga-Retreat"],
            },
            "es": {
                "service_names": ["Entrenamiento personal", "Clases grupales", "Membresía de gimnasio"],
                "service_outcomes": ["Mejor salud", "Mayor fuerza", "Pérdida de peso"],
                "audiences": ["Entusiastas del fitness", "Principiantes", "Atletas"],
                "project_names": ["Desafío de cuerpo de verano", "Entrenamiento de maratón", "Retiro de yoga"],
            },
            "fr": {
                "service_names": ["Entraînement personnel", "Cours de groupe", "Adhésion au gymnase"],
                "service_outcomes": ["Meilleure santé", "Force accrue", "Perte de poids"],
                "audiences": ["Enthousiastes du fitness", "Débutants", "Athlètes"],
                "project_names": ["Défi corps d'été", "Entraînement marathon", "Retraite yoga"],
            },
            "it": {
                "service_names": ["Allenamento personale", "Lezioni di gruppo", "Iscrizione in palestra"],
                "service_outcomes": ["Migliore salute", "Maggiore forza", "Perdita di peso"],
                "audiences": ["Appassionati di fitness", "Principianti", "Atleti"],
                "project_names": ["Sfida corpo estivo", "Allenamento maratona", "Ritiro yoga"],
            },
        },
    },
    "news": {
        "label": "News",
        "page_family": "services_projects",
        "locales": {
            "en": {
                "service_names": ["News Reporting", "Investigative Journalism", "Online Publishing"],
                "service_outcomes": ["Informed Public", "Accurate Information", "Community Engagement"],
                "audiences": ["Readers", "Subscribers", "Advertisers"],
                "project_names": ["Breaking News Coverage", "In-depth Analysis", "Community Stories"],
                "hero_kickers": ["Breaking News", "Latest Updates"],
                "hero_lines": ["Stay Informed", "Your Source for News"],
                "hero_support": ["Reliable Reporting", "In-Depth Coverage"],
                "about_lines": ["We deliver news with integrity", "Committed to truth"],
            },
            "de": {
                "service_names": ["Nachrichtenberichterstattung", "Investigativer Journalismus", "Online-Veröffentlichung"],
                "service_outcomes": ["Informierte Öffentlichkeit", "Genauer Informationen", "Gemeinschaftsengagement"],
                "audiences": ["Leser", "Abonnenten", "Werbetreibende"],
                "project_names": ["Breaking News Berichterstattung", "Tiefgehende Analyse", "Gemeinschaftsgeschichten"],
                "hero_kickers": ["Breaking News", "Neueste Updates"],
                "hero_lines": ["Bleiben Sie informiert", "Ihre Quelle für Nachrichten"],
                "hero_support": ["Zuverlässige Berichterstattung", "Tiefgehende Berichterstattung"],
                "about_lines": ["Wir liefern Nachrichten mit Integrität", "Verpflichtet zur Wahrheit"],
            },
            "es": {
                "service_names": ["Reportaje de noticias", "Periodismo de investigación", "Publicación en línea"],
                "service_outcomes": ["Público informado", "Información precisa", "Compromiso comunitario"],
                "audiences": ["Lectores", "Suscriptores", "Anunciantes"],
                "project_names": ["Cobertura de noticias de última hora", "Análisis en profundidad", "Historias comunitarias"],
                "hero_kickers": ["Últimas noticias", "Actualizaciones"],
                "hero_lines": ["Mantente informado", "Tu fuente de noticias"],
                "hero_support": ["Reportaje confiable", "Cobertura en profundidad"],
                "about_lines": ["Entregamos noticias con integridad", "Comprometidos con la verdad"],
            },
            "fr": {
                "service_names": ["Reportage d'actualités", "Journalisme d'investigation", "Publication en ligne"],
                "service_outcomes": ["Public informé", "Informations précises", "Engagement communautaire"],
                "audiences": ["Lecteurs", "Abonnés", "Annonceurs"],
                "project_names": ["Couverture d'actualités de dernière minute", "Analyse approfondie", "Histoires communautaires"],
                "hero_kickers": ["Dernières nouvelles", "Mises à jour"],
                "hero_lines": ["Restez informé", "Votre source d'informations"],
                "hero_support": ["Reportage fiable", "Couverture approfondie"],
                "about_lines": ["Nous livrons les nouvelles avec intégrité", "Engagés envers la vérité"],
            },
            "it": {
                "service_names": ["Reportage di notizie", "Giornalismo investigativo", "Pubblicazione online"],
                "service_outcomes": ["Pubblico informato", "Informazioni accurate", "Impegno comunitario"],
                "audiences": ["Lettori", "Abbonati", "Inserzionisti"],
                "project_names": ["Copertura di notizie di ultima ora", "Analisi approfondita", "Storie comunitarie"],
                "hero_kickers": ["Ultime notizie", "Aggiornamenti"],
                "hero_lines": ["Rimani informato", "La tua fonte di notizie"],
                "hero_support": ["Reportage affidabile", "Copertura approfondita"],
                "about_lines": ["Consegniamo notizie con integrità", "Impegnati per la verità"],
            },
        },
    },
    "apparel": {
        "label": "Apparel",
        "page_family": "services",
        "locales": {
            "en": {
                "service_names": ["Clothing Design", "Fashion Retail", "Custom Apparel"],
                "service_outcomes": ["Stylish Outfits", "Quality Fabrics", "Unique Designs"],
                "audiences": ["Fashion Lovers", "Shoppers", "Designers"],
                "project_names": ["Summer Collection", "Winter Line", "Bridal Wear"],
            },
            "de": {
                "service_names": ["Kleidungsdesign", "Mode-Einzelhandel", "Maßgeschneiderte Kleidung"],
                "service_outcomes": ["Stilvolle Outfits", "Qualitätsstoffe", "Einzigartige Designs"],
                "audiences": ["Mode-Liebhaber", "Einkäufer", "Designer"],
                "project_names": ["Sommerkollektion", "Winterlinie", "Brautmode"],
            },
            "es": {
                "service_names": ["Diseño de ropa", "Venta minorista de moda", "Ropa personalizada"],
                "service_outcomes": ["Trajes elegantes", "Telas de calidad", "Diseños únicos"],
                "audiences": ["Amantes de la moda", "Compradores", "Diseñadores"],
                "project_names": ["Colección de verano", "Línea de invierno", "Ropa de novia"],
            },
            "fr": {
                "service_names": ["Conception de vêtements", "Détail de mode", "Vêtements sur mesure"],
                "service_outcomes": ["Tenues élégantes", "Tissus de qualité", "Designs uniques"],
                "audiences": ["Amoureux de la mode", "Acheteurs", "Créateurs"],
                "project_names": ["Collection d'été", "Ligne d'hiver", "Tenues de mariage"],
            },
            "it": {
                "service_names": ["Design di abbigliamento", "Vendita al dettaglio di moda", "Abbigliamento su misura"],
                "service_outcomes": ["Abbigliamento elegante", "Tessuti di qualità", "Design unici"],
                "audiences": ["Amante della moda", "Acquirenti", "Designer"],
                "project_names": ["Collezione estiva", "Linea invernale", "Abbigliamento da sposa"],
            },
        },
    },
}
LOCALE_PACKS = {
    "en": {
        "html_lang": "en",
        "footer_blurb": "Public-facing microsite generated for realistic local business discovery, contact routing, and compliant legal disclosure.",
        "legal": {
            "privacy_title": "Privacy Policy",
            "cookie_title": "Cookie Policy",
            "terms_title": "Terms of Service",
            "legal_notice_title": "Legal Notice",
            "disclaimer_title": "Disclaimer",
        },
        "labels": {
            "last_updated": "Last updated",
            "overview": "Overview",
            "cta_primary": "Get Started",
            "cta_secondary": "Learn More",
            "contact": "Contact",
            "why_choose": "Why Choose Us",
            "language": "Language",
            "testimonials": "Testimonials",
            "faq": "FAQ",
            "contact_intro": "Get in Touch",
            "compliance": "Compliance",
            "cookie_text": "We use essential cookies and local storage to keep navigation stable, remember your preference, and protect basic form flows.",
            "cookie_accept": "Accept",
            "cookie_link": "Read cookie policy",
            "not_found": "Page not found",
            "back_home": "Back to home",
        },
        "geo_names": {
            "US": "United States", "CA": "Canada", "MX": "Mexico",
            "UK": "United Kingdom", "DE": "Germany", "FR": "France", "ES": "Spain", "IT": "Italy",
            "AT": "Austria", "BE": "Belgium", "BG": "Bulgaria", "CH": "Switzerland", "CY": "Cyprus",
            "CZ": "Czech Republic", "DK": "Denmark", "EE": "Estonia", "FI": "Finland", "GR": "Greece",
            "HR": "Croatia", "HU": "Hungary", "IE": "Ireland", "LT": "Lithuania", "LU": "Luxembourg",
            "LV": "Latvia", "MT": "Malta", "NL": "Netherlands", "NO": "Norway", "PL": "Poland",
            "PT": "Portugal", "RO": "Romania", "SE": "Sweden", "SI": "Slovenia", "SK": "Slovakia", "UA": "Ukraine",
            "SG": "Singapore", "JP": "Japan", "CN": "China", "KR": "South Korea", "IN": "India",
            "TH": "Thailand", "ID": "Indonesia", "MY": "Malaysia", "PH": "Philippines", "VN": "Vietnam",
            "TW": "Taiwan", "HK": "Hong Kong", "AE": "United Arab Emirates", "SA": "Saudi Arabia",
            "IL": "Israel", "TR": "Turkey", "BD": "Bangladesh", "KH": "Cambodia",
            "AU": "Australia", "NZ": "New Zealand",
            "BR": "Brazil", "AR": "Argentina", "CO": "Colombia", "CL": "Chile", "PE": "Peru",
            "VE": "Venezuela", "EC": "Ecuador", "BO": "Bolivia", "PY": "Paraguay", "UY": "Uruguay",
            "CR": "Costa Rica", "PA": "Panama", "GT": "Guatemala", "DO": "Dominican Republic",
        },
        "social_platforms": ["facebook", "twitter", "instagram"],
    },
    "de": {
        "html_lang": "de",
        "footer_blurb": "Offentliche Microsite fur lokale Anfragen, nachvollziehbare Kontaktwege und rechtskonforme Hinweise im gewahlten Markt.",
        "legal": {
            "privacy_title": "Datenschutzrichtlinie",
            "cookie_title": "Cookie-Richtlinie",
            "terms_title": "Nutzungsbedingungen",
            "legal_notice_title": "Impressum",
            "disclaimer_title": "Haftungsausschluss",
        },
        "labels": {
            "last_updated": "Zuletzt aktualisiert",
            "overview": "Überblick",
            "cta_primary": "Loslegen",
            "cta_secondary": "Mehr erfahren",
            "contact": "Kontakt",
            "why_choose": "Warum uns wählen",
            "language": "Sprache",
            "testimonials": "Bewertungen",
            "faq": "FAQ",
            "contact_intro": "Kontakt aufnehmen",
            "compliance": "Rechtliches",
            "cookie_text": "Wir nutzen notwendige Cookies und lokalen Speicher, um die Navigation stabil zu halten, Einstellungen zu speichern und Basisfunktionen zu schutzen.",
            "cookie_accept": "Akzeptieren",
            "cookie_link": "Cookie-Richtlinie lesen",
            "not_found": "Seite nicht gefunden",
            "back_home": "Zur Startseite",
        },
        "geo_names": {
            "US": "Vereinigte Staaten", "CA": "Kanada", "MX": "Mexiko",
            "UK": "Vereinigtes Königreich", "DE": "Deutschland", "FR": "Frankreich", "ES": "Spanien", "IT": "Italien",
            "AT": "Österreich", "BE": "Belgien", "BG": "Bulgarien", "CH": "Schweiz", "CY": "Zypern",
            "CZ": "Tschechien", "DK": "Dänemark", "EE": "Estland", "FI": "Finnland", "GR": "Griechenland",
            "HR": "Kroatien", "HU": "Ungarn", "IE": "Irland", "LT": "Litauen", "LU": "Luxemburg",
            "LV": "Lettland", "MT": "Malta", "NL": "Niederlande", "NO": "Norwegen", "PL": "Polen",
            "PT": "Portugal", "RO": "Rumänien", "SE": "Schweden", "SI": "Slowenien", "SK": "Slowakei", "UA": "Ukraine",
            "SG": "Singapur", "JP": "Japan", "CN": "China", "KR": "Südkorea", "IN": "Indien",
            "TH": "Thailand", "ID": "Indonesien", "MY": "Malaysia", "PH": "Philippinen", "VN": "Vietnam",
            "TW": "Taiwan", "HK": "Hongkong", "AE": "Vereinigte Arabische Emirate", "SA": "Saudi-Arabien",
            "IL": "Israel", "TR": "Türkei", "BD": "Bangladesch", "KH": "Kambodscha",
            "AU": "Australien", "NZ": "Neuseeland",
            "BR": "Brasilien", "AR": "Argentinien", "CO": "Kolumbien", "CL": "Chile", "PE": "Peru",
            "VE": "Venezuela", "EC": "Ecuador", "BO": "Bolivien", "PY": "Paraguay", "UY": "Uruguay",
            "CR": "Costa Rica", "PA": "Panama", "GT": "Guatemala", "DO": "Dominikanische Republik",
        },
        "social_platforms": ["facebook", "twitter", "instagram"],
    },
    "es": {
        "html_lang": "es",
        "footer_blurb": "Micrositio publico generado para presencia local creible, contacto verificable y documentos legales adaptados al mercado.",
        "legal": {
            "privacy_title": "Política de privacidad",
            "cookie_title": "Política de cookies",
            "terms_title": "Términos de servicio",
            "legal_notice_title": "Aviso legal",
            "disclaimer_title": "Descargo de responsabilidad",
        },
        "labels": {
            "last_updated": "Última actualización",
            "overview": "Resumen",
            "cta_primary": "Comenzar",
            "cta_secondary": "Saber más",
            "contact": "Contacto",
            "why_choose": "Por qué elegirnos",
            "language": "Idioma",
            "testimonials": "Testimonios",
            "faq": "Preguntas frecuentes",
            "contact_intro": "Ponte en contacto",
            "compliance": "Cumplimiento",
            "cookie_text": "Usamos cookies esenciales y almacenamiento local para mantener la navegacion estable, recordar preferencias y proteger funciones basicas.",
            "cookie_accept": "Aceptar",
            "cookie_link": "Leer politica de cookies",
            "not_found": "Pagina no encontrada",
            "back_home": "Volver al inicio",
        },
        "geo_names": {
            "US": "Estados Unidos", "CA": "Canadá", "MX": "México",
            "UK": "Reino Unido", "DE": "Alemania", "FR": "Francia", "ES": "España", "IT": "Italia",
            "AT": "Austria", "BE": "Bélgica", "BG": "Bulgaria", "CH": "Suiza", "CY": "Chipre",
            "CZ": "República Checa", "DK": "Dinamarca", "EE": "Estonia", "FI": "Finlandia", "GR": "Grecia",
            "HR": "Croacia", "HU": "Hungría", "IE": "Irlanda", "LT": "Lituania", "LU": "Luxemburgo",
            "LV": "Letonia", "MT": "Malta", "NL": "Países Bajos", "NO": "Noruega", "PL": "Polonia",
            "PT": "Portugal", "RO": "Rumanía", "SE": "Suecia", "SI": "Eslovenia", "SK": "Eslovaquia", "UA": "Ucrania",
            "SG": "Singapur", "JP": "Japón", "CN": "China", "KR": "Corea del Sur", "IN": "India",
            "TH": "Tailandia", "ID": "Indonesia", "MY": "Malasia", "PH": "Filipinas", "VN": "Vietnam",
            "TW": "Taiwán", "HK": "Hong Kong", "AE": "Emiratos Árabes Unidos", "SA": "Arabia Saudita",
            "IL": "Israel", "TR": "Turquía", "BD": "Bangladés", "KH": "Camboya",
            "AU": "Australia", "NZ": "Nueva Zelanda",
            "BR": "Brasil", "AR": "Argentina", "CO": "Colombia", "CL": "Chile", "PE": "Perú",
            "VE": "Venezuela", "EC": "Ecuador", "BO": "Bolivia", "PY": "Paraguay", "UY": "Uruguay",
            "CR": "Costa Rica", "PA": "Panamá", "GT": "Guatemala", "DO": "República Dominicana",
        },
        "social_platforms": ["facebook", "twitter", "instagram"],
    },
    "fr": {
        "html_lang": "fr",
        "footer_blurb": "Microsite public genere pour une presence locale credible, un parcours de contact clair et une base legale adaptee au marche.",
        "legal": {
            "privacy_title": "Politique de confidentialité",
            "cookie_title": "Politique de cookies",
            "terms_title": "Conditions d'utilisation",
            "legal_notice_title": "Mentions légales",
            "disclaimer_title": "Avis de non-responsabilité",
        },
        "labels": {
            "last_updated": "Dernière mise à jour",
            "overview": "Aperçu",
            "cta_primary": "Commencer",
            "cta_secondary": "En savoir plus",
            "contact": "Contact",
            "why_choose": "Pourquoi nous choisir",
            "language": "Langue",
            "testimonials": "Témoignages",
            "faq": "FAQ",
            "contact_intro": "Entrer en contact",
            "compliance": "Conformite",
            "cookie_text": "Nous utilisons des cookies essentiels et du stockage local pour garder la navigation stable, memoriser vos choix et proteger les fonctions de base.",
            "cookie_accept": "Accepter",
            "cookie_link": "Lire la politique cookies",
            "not_found": "Page introuvable",
            "back_home": "Retour a l'accueil",
        },
        "geo_names": {
            "US": "États-Unis", "CA": "Canada", "MX": "Mexique",
            "UK": "Royaume-Uni", "DE": "Allemagne", "FR": "France", "ES": "Espagne", "IT": "Italie",
            "AT": "Autriche", "BE": "Belgique", "BG": "Bulgarie", "CH": "Suisse", "CY": "Chypre",
            "CZ": "République tchèque", "DK": "Danemark", "EE": "Estonie", "FI": "Finlande", "GR": "Grèce",
            "HR": "Croatie", "HU": "Hongrie", "IE": "Irlande", "LT": "Lituanie", "LU": "Luxembourg",
            "LV": "Lettonie", "MT": "Malte", "NL": "Pays-Bas", "NO": "Norvège", "PL": "Pologne",
            "PT": "Portugal", "RO": "Roumanie", "SE": "Suède", "SI": "Slovénie", "SK": "Slovaquie", "UA": "Ukraine",
            "SG": "Singapour", "JP": "Japon", "CN": "Chine", "KR": "Corée du Sud", "IN": "Inde",
            "TH": "Thaïlande", "ID": "Indonésie", "MY": "Malaisie", "PH": "Philippines", "VN": "Vietnam",
            "TW": "Taïwan", "HK": "Hong Kong", "AE": "Émirats arabes unis", "SA": "Arabie saoudite",
            "IL": "Israël", "TR": "Turquie", "BD": "Bangladesh", "KH": "Cambodge",
            "AU": "Australie", "NZ": "Nouvelle-Zélande",
            "BR": "Brésil", "AR": "Argentine", "CO": "Colombie", "CL": "Chili", "PE": "Pérou",
            "VE": "Venezuela", "EC": "Équateur", "BO": "Bolivie", "PY": "Paraguay", "UY": "Uruguay",
            "CR": "Costa Rica", "PA": "Panama", "GT": "Guatemala", "DO": "République dominicaine",
        },
        "social_platforms": ["facebook", "twitter", "instagram"],
    },
    "it": {
        "html_lang": "it",
        "footer_blurb": "Microsito pubblico generato per una presenza locale credibile, contatti coerenti e documentazione legale allineata al mercato.",
        "legal": {
            "privacy_title": "Informativa sulla privacy",
            "cookie_title": "Politica sui cookie",
            "terms_title": "Termini di servizio",
            "legal_notice_title": "Nota legale",
            "disclaimer_title": "Disclaimer",
        },
        "labels": {
            "last_updated": "Ultimo aggiornamento",
            "overview": "Panoramica",
            "cta_primary": "Inizia",
            "cta_secondary": "Scopri di più",
            "contact": "Contatto",
            "why_choose": "Perché scegliere noi",
            "language": "Lingua",
            "testimonials": "Testimonianze",
            "faq": "FAQ",
            "contact_intro": "Mettiti in contatto",
            "compliance": "Conformita",
            "cookie_text": "Usiamo cookie essenziali e storage locale per mantenere stabile la navigazione, ricordare le preferenze e proteggere le funzioni di base.",
            "cookie_accept": "Accetta",
            "cookie_link": "Leggi la cookie policy",
            "not_found": "Pagina non trovata",
            "back_home": "Torna alla home",
        },
        "geo_names": {
            "US": "Stati Uniti", "CA": "Canada", "MX": "Messico",
            "UK": "Regno Unito", "DE": "Germania", "FR": "Francia", "ES": "Spagna", "IT": "Italia",
            "AT": "Austria", "BE": "Belgio", "BG": "Bulgaria", "CH": "Svizzera", "CY": "Cipro",
            "CZ": "Repubblica Ceca", "DK": "Danimarca", "EE": "Estonia", "FI": "Finlandia", "GR": "Grecia",
            "HR": "Croazia", "HU": "Ungheria", "IE": "Irlanda", "LT": "Lituania", "LU": "Lussemburgo",
            "LV": "Lettonia", "MT": "Malta", "NL": "Paesi Bassi", "NO": "Norvegia", "PL": "Polonia",
            "PT": "Portogallo", "RO": "Romania", "SE": "Svezia", "SI": "Slovenia", "SK": "Slovacchia", "UA": "Ucraina",
            "SG": "Singapore", "JP": "Giappone", "CN": "Cina", "KR": "Corea del Sud", "IN": "India",
            "TH": "Tailandia", "ID": "Indonesia", "MY": "Malesia", "PH": "Filippine", "VN": "Vietnam",
            "TW": "Taiwan", "HK": "Hong Kong", "AE": "Emirati Arabi Uniti", "SA": "Arabia Saudita",
            "IL": "Israele", "TR": "Turchia", "BD": "Bangladesh", "KH": "Cambogia",
            "AU": "Australia", "NZ": "Nuova Zelanda",
            "BR": "Brasile", "AR": "Argentina", "CO": "Colombia", "CL": "Cile", "PE": "Perù",
            "VE": "Venezuela", "EC": "Ecuador", "BO": "Bolivia", "PY": "Paraguay", "UY": "Uruguay",
            "CR": "Costa Rica", "PA": "Panama", "GT": "Guatemala", "DO": "Repubblica Dominicana",
        },
        "social_platforms": ["facebook", "twitter", "instagram"],
    },
}
GEO_PACKS = {
    "US": {"legal": {"jurisdiction": "United States", "privacy_reference": "CCPA", "cookie_reference": "CCPA", "regulator": "California Privacy Protection Agency"}, "company_suffix": "LLC", "phone_area_codes": ["212", "213", "310", "415", "510", "650", "702", "818", "925"], "phone_country_code": "+1", "phone_pattern": "{cc} ({area}) {first}-{second}", "cities": [("New York", "NY", ["Broadway", "5th Ave", "Wall St"]), ("Los Angeles", "CA", ["Hollywood Blvd", "Sunset Blvd", "Wilshire Blvd"]), ("Chicago", "IL", ["Michigan Ave", "Wabash Ave", "State St"])], "postal_codes": ["10001", "90210", "60601"]},
    "UK": {"legal": {"jurisdiction": "United Kingdom", "privacy_reference": "UK GDPR", "cookie_reference": "UK GDPR", "regulator": "Information Commissioner's Office"}, "company_suffix": "Ltd", "phone_area_codes": ["020", "0161", "0121", "0113", "0141", "0151", "0131", "01223", "01603"], "phone_country_code": "+44", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("London", "England", ["Oxford St", "Regent St", "Baker St"]), ("Manchester", "England", ["Market St", "Deansgate", "King St"]), ("Birmingham", "England", ["Bullring", "Broad St", "New St"])], "postal_codes": ["SW1A 1AA", "M1 1AA", "B1 1AA"]},
    "CA": {"legal": {"jurisdiction": "Canada", "privacy_reference": "PIPEDA", "cookie_reference": "PIPEDA", "regulator": "Office of the Privacy Commissioner of Canada"}, "company_suffix": "Inc", "phone_area_codes": ["416", "514", "604", "778", "902", "204", "306", "403", "587"], "phone_country_code": "+1", "phone_pattern": "{cc} ({area}) {first}-{second}", "cities": [("Toronto", "ON", ["Yonge St", "Queen St", "King St"]), ("Montreal", "QC", ["Rue Sainte-Catherine", "Rue Saint-Denis", "Boulevard Saint-Laurent"]), ("Vancouver", "BC", ["Granville St", "Robson St", "Georgia St"])], "postal_codes": ["M5H 2N2", "H3B 1A1", "V6B 1A1"]},
    "AU": {"legal": {"jurisdiction": "Australia", "privacy_reference": "Privacy Act 1988", "cookie_reference": "Privacy Act 1988", "regulator": "Office of the Australian Information Commissioner"}, "company_suffix": "Pty Ltd", "phone_area_codes": ["02", "03", "07", "08", "04"], "phone_country_code": "+61", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Sydney", "NSW", ["George St", "Pitt St", "Oxford St"]), ("Melbourne", "VIC", ["Collins St", "Swanston St", "Flinders St"]), ("Brisbane", "QLD", ["Queen St", "Edward St", "Adelaide St"])], "postal_codes": ["2000", "3000", "4000"]},
    "DE": {"legal": {"jurisdiction": "Germany", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Federal Commissioner for Data Protection and Freedom of Information"}, "company_suffix": "GmbH", "phone_area_codes": ["030", "040", "069", "089", "0221", "0201", "0211", "0611", "0711"], "phone_country_code": "+49", "phone_pattern": "{cc} {area} {first}{second}", "cities": [("Berlin", "Berlin", ["Unter den Linden", "Friedrichstraße", "Alexanderplatz"]), ("Munich", "Bavaria", ["Marienplatz", "Maximilianstraße", "Kaufingerstraße"]), ("Hamburg", "Hamburg", ["Reeperbahn", "Jungfernstieg", "Mönckebergstraße"])], "postal_codes": ["10117", "80331", "20095"]},
    "FR": {"legal": {"jurisdiction": "France", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Commission Nationale de l'Informatique et des Libertés"}, "company_suffix": "SARL", "phone_area_codes": ["01", "02", "03", "04", "05", "06", "07", "08", "09"], "phone_country_code": "+33", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Paris", "Île-de-France", ["Champs-Élysées", "Rue de Rivoli", "Boulevard Haussmann"]), ("Lyon", "Auvergne-Rhône-Alpes", ["Rue de la République", "Rue Victor Hugo", "Rue Mercière"]), ("Marseille", "Provence-Alpes-Côte d'Azur", ["La Canebière", "Rue Saint-Ferréol", "Cours Julien"])], "postal_codes": ["75001", "69001", "13001"]},
    "ES": {"legal": {"jurisdiction": "Spain", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Spanish Data Protection Agency"}, "company_suffix": "SL", "phone_area_codes": ["91", "93", "95", "96", "97", "98", "81", "82", "83"], "phone_country_code": "+34", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Madrid", "Madrid", ["Gran Vía", "Paseo de la Castellana", "Calle Mayor"]), ("Barcelona", "Catalonia", ["La Rambla", "Passeig de Gràcia", "Carrer de Ferran"]), ("Valencia", "Valencia", ["Calle de la Paz", "Calle Colón", "Gran Vía del Marqués del Turia"])], "postal_codes": ["28001", "08001", "46001"]},
    "IT": {"legal": {"jurisdiction": "Italy", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Italian Data Protection Authority"}, "company_suffix": "SRL", "phone_area_codes": ["02", "06", "010", "055", "041", "081", "091", "095", "011"], "phone_country_code": "+39", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Rome", "Lazio", ["Via del Corso", "Via Condotti", "Via dei Condotti"]), ("Milan", "Lombardy", ["Via Montenapoleone", "Corso Vittorio Emanuele", "Via della Spiga"]), ("Florence", "Tuscany", ["Piazza della Signoria", "Via dei Calzaiuoli", "Ponte Vecchio"])], "postal_codes": ["00100", "20121", "50122"]},
    "SG": {"legal": {"jurisdiction": "Singapore", "privacy_reference": "PDPA", "cookie_reference": "PDPA", "regulator": "Personal Data Protection Commission"}, "company_suffix": "Pte Ltd", "phone_area_codes": ["65"], "phone_country_code": "+65", "phone_pattern": "{cc} {first}{second}", "cities": [("Singapore", "Singapore", ["Orchard Road", "Marina Bay Sands", "Chinatown"])], "postal_codes": ["018956", "038983", "059911"]},
    # Europe
    "AT": {"legal": {"jurisdiction": "Austria", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Austrian Data Protection Authority"}, "company_suffix": "GmbH", "phone_area_codes": ["01", "0316", "0662", "0732", "0512"], "phone_country_code": "+43", "phone_pattern": "{cc} {area} {first}{second}", "cities": [("Vienna", "Vienna", ["Mariahilfer Straße", "Kärntner Straße", "Graben"]), ("Graz", "Styria", ["Herrengasse", "Annenstraße", "Sporgasse"]), ("Salzburg", "Salzburg", ["Getreidegasse", "Linzer Gasse", "Staatsbrücke"])], "postal_codes": ["1010", "8010", "5020"]},
    "BE": {"legal": {"jurisdiction": "Belgium", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Belgian Data Protection Authority"}, "company_suffix": "BV", "phone_area_codes": ["02", "03", "04", "09", "011"], "phone_country_code": "+32", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Brussels", "Brussels", ["Boulevard Anspach", "Rue Neuve", "Avenue Louise"]), ("Antwerp", "Flanders", ["Meir", "Schoenmarkt", "Nationalestraat"]), ("Ghent", "Flanders", ["Veldstraat", "Korenmarkt", "Langemunt"])], "postal_codes": ["1000", "2000", "9000"]},
    "BG": {"legal": {"jurisdiction": "Bulgaria", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Commission for Personal Data Protection"}, "company_suffix": "OOD", "phone_area_codes": ["02", "032", "052", "056", "066"], "phone_country_code": "+359", "phone_pattern": "{cc} {area} {first}{second}", "cities": [("Sofia", "Sofia", ["Vitosha Blvd", "Graf Ignatiev St", "Patriarh Evtimiy Blvd"]), ("Plovdiv", "Plovdiv", ["Knyaz Alexander I St", "Main Pedestrian St"]), ("Varna", "Varna", ["Vladislav Varnenchik Blvd", "Slivnitsa Blvd"])], "postal_codes": ["1000", "4000", "9000"]},
    "CH": {"legal": {"jurisdiction": "Switzerland", "privacy_reference": "nDSG", "cookie_reference": "nDSG", "regulator": "Federal Data Protection and Information Commissioner"}, "company_suffix": "GmbH", "phone_area_codes": ["044", "022", "061", "031", "021"], "phone_country_code": "+41", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Zurich", "Zurich", ["Bahnhofstrasse", "Limmatquai", "Rämistrasse"]), ("Geneva", "Geneva", ["Rue du Rhône", "Rue de Rive", "Rue du Marché"]), ("Basel", "Basel", ["Freie Strasse", "Spalenvorstadt", "Marktplatz"])], "postal_codes": ["8001", "1201", "4001"]},
    "CY": {"legal": {"jurisdiction": "Cyprus", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Commissioner for Personal Data Protection"}, "company_suffix": "Ltd", "phone_area_codes": ["22", "25", "24", "26"], "phone_country_code": "+357", "phone_pattern": "{cc} {area} {first}{second}", "cities": [("Nicosia", "Nicosia", ["Ledra St", "Makarios Ave", "Stasikratous St"]), ("Limassol", "Limassol", ["Makarios III Ave", "Archbishop Kyprianou St"]), ("Larnaca", "Larnaca", ["Finikoudes Promenade", "Ermou St"])], "postal_codes": ["1010", "3040", "7100"]},
    "CZ": {"legal": {"jurisdiction": "Czech Republic", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Office for Personal Data Protection"}, "company_suffix": "s.r.o.", "phone_area_codes": ["2", "5", "37", "38", "39"], "phone_country_code": "+420", "phone_pattern": "{cc} {area}{first}{second}", "cities": [("Prague", "Prague", ["Wenceslas Square", "Na Příkopě", "Old Town Square"]), ("Brno", "South Moravia", ["Náměstí Svobody", "Česká", "Masarykova"]), ("Ostrava", "Moravian-Silesian", ["Masarykovo náměstí", "28. října"])], "postal_codes": ["110 00", "602 00", "702 00"]},
    "DK": {"legal": {"jurisdiction": "Denmark", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Danish Data Protection Agency"}, "company_suffix": "ApS", "phone_area_codes": ["33", "35", "38", "43", "44"], "phone_country_code": "+45", "phone_pattern": "{cc} {first} {second}", "cities": [("Copenhagen", "Capital", ["Strøget", "Nørrebrogade", "Vesterbrogade"]), ("Aarhus", "Central Jutland", ["Strøget", "Åboulevarden", "Ryesgade"]), ("Odense", "Southern Denmark", ["Vestergade", "Kongensgade", "Brandts Passage"])], "postal_codes": ["1050", "8000", "5000"]},
    "EE": {"legal": {"jurisdiction": "Estonia", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Estonian Data Protection Inspectorate"}, "company_suffix": "OÜ", "phone_area_codes": ["6", "7", "5"], "phone_country_code": "+372", "phone_pattern": "{cc} {first}{second}", "cities": [("Tallinn", "Harju", ["Viru St", "Narva mnt", "Pärnu mnt"]), ("Tartu", "Tartu", ["Ülikooli St", "Küüni St", "Rüütli St"]), ("Pärnu", "Pärnu", ["Rüütli St", "Kuninga St"])], "postal_codes": ["10111", "51003", "80010"]},
    "FI": {"legal": {"jurisdiction": "Finland", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Office of the Data Protection Ombudsman"}, "company_suffix": "Oy", "phone_area_codes": ["09", "03", "02", "06", "08"], "phone_country_code": "+358", "phone_pattern": "{cc} {area} {first}{second}", "cities": [("Helsinki", "Uusimaa", ["Mannerheimintie", "Aleksanterinkatu", "Esplanadi"]), ("Tampere", "Pirkanmaa", ["Hämeenkatu", "Satakunnankatu", "Aleksis Kiven katu"]), ("Turku", "Finland Proper", ["Yliopistonkatu", "Eerikinkatu", "Kauppiaskatu"])], "postal_codes": ["00100", "33100", "20100"]},
    "GR": {"legal": {"jurisdiction": "Greece", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Hellenic Data Protection Authority"}, "company_suffix": "A.E.", "phone_area_codes": ["210", "231", "281", "261", "2310"], "phone_country_code": "+30", "phone_pattern": "{cc} {area} {first}{second}", "cities": [("Athens", "Attica", ["Ermou St", "Syntagma Square", "Monastiraki Square"]), ("Thessaloniki", "Central Macedonia", ["Tsimiski St", "Aristotelous Square", "Egnatia St"]), ("Heraklion", "Crete", ["25th August St", "1866 Square"])], "postal_codes": ["10431", "54626", "71202"]},
    "HR": {"legal": {"jurisdiction": "Croatia", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Croatian Personal Data Protection Agency"}, "company_suffix": "d.o.o.", "phone_area_codes": ["01", "021", "023", "031", "051"], "phone_country_code": "+385", "phone_pattern": "{cc} {area} {first}{second}", "cities": [("Zagreb", "Zagreb", ["Ilica St", "Jelačić Square", "Tkalčićeva St"]), ("Split", "Split-Dalmatia", ["Marmontova St", "Riva Promenade", "Makarska St"]), ("Dubrovnik", "Dubrovnik-Neretva", ["Stradun", "Od Puča St"])], "postal_codes": ["10000", "21000", "20000"]},
    "HU": {"legal": {"jurisdiction": "Hungary", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "National Authority for Data Protection and Freedom of Information"}, "company_suffix": "Kft.", "phone_area_codes": ["1", "52", "62", "46", "56"], "phone_country_code": "+36", "phone_pattern": "{cc} {area} {first}{second}", "cities": [("Budapest", "Budapest", ["Váci St", "Andrássy Ave", "Kossuth Lajos St"]), ("Debrecen", "Hajdú-Bihar", ["Piac St", "Hatvan St"]), ("Miskolc", "Borsod-Abaúj-Zemplén", ["Széchenyi St", "Városház tér"])], "postal_codes": ["1051", "4025", "3525"]},
    "IE": {"legal": {"jurisdiction": "Ireland", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Data Protection Commission"}, "company_suffix": "Ltd", "phone_area_codes": ["01", "021", "091", "061", "051"], "phone_country_code": "+353", "phone_pattern": "{cc} {area} {first}{second}", "cities": [("Dublin", "Leinster", ["O'Connell St", "Grafton St", "Henry St"]), ("Cork", "Munster", ["Patrick St", "Oliver Plunkett St", "Grand Parade"]), ("Galway", "Connacht", ["Shop St", "Eyre Square", "Mainguard St"])], "postal_codes": ["D01", "T12", "H91"]},
    "LT": {"legal": {"jurisdiction": "Lithuania", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "State Data Protection Inspectorate"}, "company_suffix": "UAB", "phone_area_codes": ["5", "37", "46", "41", "45"], "phone_country_code": "+370", "phone_pattern": "{cc} {area} {first}{second}", "cities": [("Vilnius", "Vilnius County", ["Gedimino Ave", "Pilies St", "Didžioji St"]), ("Kaunas", "Kaunas County", ["Laisvės Ave", "Vilniaus St"]), ("Klaipėda", "Klaipėda County", ["Tiltų St", "Herkaus Manto St"])], "postal_codes": ["01100", "44280", "92123"]},
    "LU": {"legal": {"jurisdiction": "Luxembourg", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "National Commission for Data Protection"}, "company_suffix": "S.à r.l.", "phone_area_codes": ["2", "4", "5", "6"], "phone_country_code": "+352", "phone_pattern": "{cc} {area}{first}{second}", "cities": [("Luxembourg City", "Luxembourg", ["Grande-Rue", "Rue Philippe II", "Avenue de la Gare"]), ("Esch-sur-Alzette", "Esch-sur-Alzette", ["Rue de l'Alzette", "Rue de la Libération"]), ("Differdange", "Differdange", ["Place du Marché"])], "postal_codes": ["L-1111", "L-4010", "L-4501"]},
    "LV": {"legal": {"jurisdiction": "Latvia", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Data State Inspectorate"}, "company_suffix": "SIA", "phone_area_codes": ["6", "7", "2"], "phone_country_code": "+371", "phone_pattern": "{cc} {first} {second}", "cities": [("Riga", "Riga", ["Brīvības Blvd", "Tērbatas St", "Elizabetes St"]), ("Daugavpils", "Daugavpils", ["Rīgas St", "Vienības St"]), ("Liepāja", "Liepāja", ["Lielā St", "Jūras St"])], "postal_codes": ["LV-1001", "LV-5401", "LV-3401"]},
    "MT": {"legal": {"jurisdiction": "Malta", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Information and Data Protection Commissioner"}, "company_suffix": "Ltd", "phone_area_codes": ["21", "22", "23", "27"], "phone_country_code": "+356", "phone_pattern": "{cc} {area}{first}{second}", "cities": [("Valletta", "South Eastern", ["Republic St", "Merchants St", "Old Bakery St"]), ("Sliema", "Northern", ["The Strand", "Tower Road", "High St"]), ("St Julian's", "Northern", ["St George's Road", "Spinola Rd"])], "postal_codes": ["VLT 1110", "SLM 1013", "STJ 1027"]},
    "NL": {"legal": {"jurisdiction": "Netherlands", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Dutch Data Protection Authority"}, "company_suffix": "B.V.", "phone_area_codes": ["020", "010", "030", "040", "070"], "phone_country_code": "+31", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Amsterdam", "North Holland", ["Damrak", "Kalverstraat", "P.C. Hooftstraat"]), ("Rotterdam", "South Holland", ["Lijnbaan", "Coolsingel", "Blaak"]), ("The Hague", "South Holland", ["Lange Voorhout", "Spuistraat", "Denneweg"])], "postal_codes": ["1012 AB", "3011 AB", "2511 AB"]},
    "NO": {"legal": {"jurisdiction": "Norway", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Norwegian Data Protection Authority"}, "company_suffix": "AS", "phone_area_codes": ["22", "23", "55", "73", "51"], "phone_country_code": "+47", "phone_pattern": "{cc} {first} {second}", "cities": [("Oslo", "Oslo", ["Karl Johans gate", "Aker Brygge", "Grünerløkka"]), ("Bergen", "Vestland", ["Bryggen", "Torgallmenningen", "Strandgaten"]), ("Trondheim", "Trøndelag", ["Nordre gate", "Olav Tryggvasons gate"])], "postal_codes": ["0150", "5003", "7013"]},
    "PL": {"legal": {"jurisdiction": "Poland", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Personal Data Protection Office"}, "company_suffix": "Sp. z o.o.", "phone_area_codes": ["22", "12", "71", "61", "42"], "phone_country_code": "+48", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Warsaw", "Masovian", ["Nowy Świat", "Krakowskie Przedmieście", "Marszałkowska"]), ("Kraków", "Lesser Poland", ["Floriańska", "Grodzka", "Rynek Główny"]), ("Wrocław", "Lower Silesian", ["Świdnicka", "Oławska", "Rynek"])], "postal_codes": ["00-001", "30-001", "50-001"]},
    "PT": {"legal": {"jurisdiction": "Portugal", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "National Data Protection Commission"}, "company_suffix": "Lda", "phone_area_codes": ["21", "22", "289", "253", "231"], "phone_country_code": "+351", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Lisbon", "Lisbon", ["Avenida da Liberdade", "Rua Augusta", "Rua do Ouro"]), ("Porto", "Porto", ["Rua de Santa Catarina", "Avenida dos Aliados", "Rua das Flores"]), ("Faro", "Algarve", ["Rua de Santo António", "Rua Conselheiro Bivar"])], "postal_codes": ["1100-001", "4000-001", "8000-001"]},
    "RO": {"legal": {"jurisdiction": "Romania", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "National Supervisory Authority for Personal Data Processing"}, "company_suffix": "S.R.L.", "phone_area_codes": ["021", "0264", "0256", "0232", "0269"], "phone_country_code": "+40", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Bucharest", "Ilfov", ["Calea Victoriei", "Bulevardul Unirii", "Strada Lipscani"]), ("Cluj-Napoca", "Cluj", ["Calea Turzii", "Strada Memorandumului"]), ("Timișoara", "Timiș", ["Bulevardul Mihai Eminescu", "Piața Victoriei"])], "postal_codes": ["010001", "400001", "300001"]},
    "SE": {"legal": {"jurisdiction": "Sweden", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Swedish Authority for Privacy Protection"}, "company_suffix": "AB", "phone_area_codes": ["08", "031", "040", "011", "013"], "phone_country_code": "+46", "phone_pattern": "{cc} {area}-{first} {second}", "cities": [("Stockholm", "Stockholm", ["Drottninggatan", "Kungsgatan", "Birger Jarlsgatan"]), ("Gothenburg", "Västra Götaland", ["Avenyn", "Kungsportsavenyn", "Kungsgatan"]), ("Malmö", "Skåne", ["Södra Förstadsgatan", "Amiralsgatan", "Davidshallsgatan"])], "postal_codes": ["111 20", "400 10", "211 20"]},
    "SI": {"legal": {"jurisdiction": "Slovenia", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Information Commissioner"}, "company_suffix": "d.o.o.", "phone_area_codes": ["01", "02", "03", "04", "05"], "phone_country_code": "+386", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Ljubljana", "Ljubljana", ["Čopova St", "Mestni trg", "Stari trg"]), ("Maribor", "Maribor", ["Glavni trg", "Gosposvetska cesta"]), ("Celje", "Celje", ["Krekov trg", "Prešernova ulica"])], "postal_codes": ["1000", "2000", "3000"]},
    "SK": {"legal": {"jurisdiction": "Slovakia", "privacy_reference": "GDPR", "cookie_reference": "GDPR", "regulator": "Office for Personal Data Protection"}, "company_suffix": "s.r.o.", "phone_area_codes": ["02", "055", "048", "041", "037"], "phone_country_code": "+421", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Bratislava", "Bratislava", ["Obchodná St", "Michalská St", "Hviezdoslavovo náměstie"]), ("Košice", "Košice", ["Hlavná St", "Mlynská St"]), ("Prešov", "Prešov", ["Hlavná St", "Námestie mieru"])], "postal_codes": ["811 01", "040 01", "080 01"]},
    "UA": {"legal": {"jurisdiction": "Ukraine", "privacy_reference": "Law on Personal Data Protection", "cookie_reference": "Law on Personal Data Protection", "regulator": "Commissioner for Human Rights"}, "company_suffix": "ТОВ", "phone_area_codes": ["044", "032", "057", "062", "048"], "phone_country_code": "+380", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Kyiv", "Kyiv", ["Khreshchatyk St", "Bankova St", "Kharkivske Shose"]), ("Lviv", "Lviv Oblast", ["Prospect Svobody", "Rynok Square", "Shevchenka Ave"]), ("Odessa", "Odessa Oblast", ["Derybasivska St", "Prymorsky Blvd"])], "postal_codes": ["01001", "79000", "65000"]},
    # Asia
    "JP": {"legal": {"jurisdiction": "Japan", "privacy_reference": "APPI", "cookie_reference": "APPI", "regulator": "Personal Information Protection Commission"}, "company_suffix": "K.K.", "phone_area_codes": ["03", "06", "075", "052", "011"], "phone_country_code": "+81", "phone_pattern": "{cc} {area}-{first}-{second}", "cities": [("Tokyo", "Tokyo", ["Shibuya", "Shinjuku", "Ginza"]), ("Osaka", "Osaka", ["Dotonbori", "Shinsaibashi", "Namba"]), ("Kyoto", "Kyoto", ["Shijo-dori", "Kawaramachi", "Gion"])], "postal_codes": ["100-0001", "530-0001", "604-8006"]},
    "CN": {"legal": {"jurisdiction": "China", "privacy_reference": "PIPL", "cookie_reference": "PIPL", "regulator": "Cyberspace Administration of China"}, "company_suffix": "Co., Ltd.", "phone_area_codes": ["010", "021", "020", "0755", "028"], "phone_country_code": "+86", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Beijing", "Beijing", ["Wangfujing Ave", "Chang'an Ave", "Sanlitun"]), ("Shanghai", "Shanghai", ["Nanjing Rd", "Huaihai Rd", "The Bund"]), ("Guangzhou", "Guangdong", ["Beijing Rd", "Tianhe Rd", "Zhujiang New Town"])], "postal_codes": ["100000", "200000", "510000"]},
    "KR": {"legal": {"jurisdiction": "South Korea", "privacy_reference": "PIPA", "cookie_reference": "PIPA", "regulator": "Personal Information Protection Commission"}, "company_suffix": "Co., Ltd.", "phone_area_codes": ["02", "051", "053", "032", "062"], "phone_country_code": "+82", "phone_pattern": "{cc} {area}-{first}-{second}", "cities": [("Seoul", "Seoul", ["Myeongdong", "Gangnam-daero", "Insa-dong"]), ("Busan", "Busan", ["Haeundae-ro", "Seomyeon", "Gwangalli"]), ("Incheon", "Incheon", ["Bupyeong-daero", "Sinpo-dong"])], "postal_codes": ["04524", "48958", "21565"]},
    "IN": {"legal": {"jurisdiction": "India", "privacy_reference": "DPDPA", "cookie_reference": "DPDPA", "regulator": "Data Protection Board of India"}, "company_suffix": "Pvt Ltd", "phone_area_codes": ["022", "011", "080", "033", "044"], "phone_country_code": "+91", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Mumbai", "Maharashtra", ["Marine Drive", "MG Road", "Colaba Causeway"]), ("Delhi", "Delhi", ["Connaught Place", "Karol Bagh", "Chandni Chowk"]), ("Bangalore", "Karnataka", ["MG Road", "Brigade Rd", "Commercial St"])], "postal_codes": ["400001", "110001", "560001"]},
    "TH": {"legal": {"jurisdiction": "Thailand", "privacy_reference": "PDPA", "cookie_reference": "PDPA", "regulator": "Personal Data Protection Committee"}, "company_suffix": "Co., Ltd.", "phone_area_codes": ["02", "053", "076", "043", "044"], "phone_country_code": "+66", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Bangkok", "Bangkok", ["Sukhumvit Rd", "Silom Rd", "Khao San Rd"]), ("Chiang Mai", "Chiang Mai", ["Nimmanhaemin Rd", "Tha Phae Rd", "Ratchadamnoen Rd"]), ("Phuket", "Phuket", ["Thalang Rd", "Patong Beach Rd"])], "postal_codes": ["10100", "50000", "83000"]},
    "ID": {"legal": {"jurisdiction": "Indonesia", "privacy_reference": "PDP Law", "cookie_reference": "PDP Law", "regulator": "Ministry of Communication and Information Technology"}, "company_suffix": "PT", "phone_area_codes": ["021", "031", "022", "024", "061"], "phone_country_code": "+62", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Jakarta", "DKI Jakarta", ["Jl. Sudirman", "Jl. Thamrin", "Jl. Gatot Subroto"]), ("Surabaya", "East Java", ["Jl. Pemuda", "Jl. Ahmad Yani", "Jl. Embong Malang"]), ("Bandung", "West Java", ["Jl. Asia Afrika", "Jl. Braga", "Jl. Dago"])], "postal_codes": ["10110", "60111", "40111"]},
    "MY": {"legal": {"jurisdiction": "Malaysia", "privacy_reference": "PDPA", "cookie_reference": "PDPA", "regulator": "Department of Personal Data Protection"}, "company_suffix": "Sdn. Bhd.", "phone_area_codes": ["03", "04", "05", "07", "09"], "phone_country_code": "+60", "phone_pattern": "{cc} {area}-{first} {second}", "cities": [("Kuala Lumpur", "KL", ["Jalan Bukit Bintang", "Jalan Ampang", "KLCC"]), ("Penang", "Penang", ["Jalan Penang", "Gurney Drive", "Jalan Sultan Ahmad Shah"]), ("Johor Bahru", "Johor", ["Jalan Wong Ah Fook", "Jalan Trus"])], "postal_codes": ["50000", "10000", "80000"]},
    "PH": {"legal": {"jurisdiction": "Philippines", "privacy_reference": "Data Privacy Act", "cookie_reference": "Data Privacy Act", "regulator": "National Privacy Commission"}, "company_suffix": "Inc.", "phone_area_codes": ["02", "032", "082", "074", "072"], "phone_country_code": "+63", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Manila", "Metro Manila", ["Ayala Ave", "EDSA", "Roxas Blvd"]), ("Cebu City", "Cebu", ["Colon St", "Osmena Blvd", "Gaisano Rd"]), ("Davao City", "Davao del Sur", ["Quirino Ave", "JP Laurel Ave"])], "postal_codes": ["1000", "6000", "8000"]},
    "VN": {"legal": {"jurisdiction": "Vietnam", "privacy_reference": "Cybersecurity Law", "cookie_reference": "Cybersecurity Law", "regulator": "Ministry of Information and Communications"}, "company_suffix": "Co., Ltd.", "phone_area_codes": ["028", "024", "0236", "0225", "0292"], "phone_country_code": "+84", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Ho Chi Minh City", "Ho Chi Minh", ["Nguyen Hue Blvd", "Dong Khoi St", "Le Loi Blvd"]), ("Hanoi", "Hanoi", ["Hoan Kiem Lake", "Hang Bai St", "Ba Dinh Square"]), ("Da Nang", "Da Nang", ["Bach Dang St", "Nguyen Van Linh St"])], "postal_codes": ["700000", "100000", "550000"]},
    "TW": {"legal": {"jurisdiction": "Taiwan", "privacy_reference": "PDPA", "cookie_reference": "PDPA", "regulator": "National Development Council"}, "company_suffix": "Co., Ltd.", "phone_area_codes": ["02", "07", "04", "06", "03"], "phone_country_code": "+886", "phone_pattern": "{cc} {area}-{first}-{second}", "cities": [("Taipei", "Taipei", ["Zhongxiao E Rd", "Dunhua N Rd", "Zhongshan N Rd"]), ("Kaohsiung", "Kaohsiung", ["Zhongzheng 4th Rd", "Zhonghua 3rd Rd"]), ("Taichung", "Taichung", ["Taiwan Blvd", "Wenxin Rd"])], "postal_codes": ["100", "800", "400"]},
    "HK": {"legal": {"jurisdiction": "Hong Kong", "privacy_reference": "PDPO", "cookie_reference": "PDPO", "regulator": "Office of the Privacy Commissioner for Personal Data"}, "company_suffix": "Ltd.", "phone_area_codes": ["852"], "phone_country_code": "+852", "phone_pattern": "{cc} {first} {second}", "cities": [("Hong Kong", "HK Island", ["Nathan Rd", "Causeway Bay", "Des Voeux Rd"]), ("Kowloon", "Kowloon", ["Canton Rd", "Sai Yeung Choi St", "Mong Kok Rd"]), ("New Territories", "New Territories", ["Castle Peak Rd", "Sha Tin Centre St"])], "postal_codes": ["999077", "999077", "999077"]},
    "AE": {"legal": {"jurisdiction": "United Arab Emirates", "privacy_reference": "PDPL", "cookie_reference": "PDPL", "regulator": "UAE Data Office"}, "company_suffix": "LLC", "phone_area_codes": ["04", "02", "06", "07", "09"], "phone_country_code": "+971", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Dubai", "Dubai", ["Sheikh Zayed Rd", "Jumeirah Beach Rd", "Al Wasl Rd"]), ("Abu Dhabi", "Abu Dhabi", ["Corniche Rd", "Hamdan St", "Khalidiyah St"]), ("Sharjah", "Sharjah", ["King Faisal St", "Al Arouba St"])], "postal_codes": ["00000", "00001", "00002"]},
    "SA": {"legal": {"jurisdiction": "Saudi Arabia", "privacy_reference": "PDPL", "cookie_reference": "PDPL", "regulator": "Saudi Data and AI Authority"}, "company_suffix": "LLC", "phone_area_codes": ["011", "012", "013", "016", "017"], "phone_country_code": "+966", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Riyadh", "Riyadh", ["King Fahd Rd", "Olaya St", "Tahlia St"]), ("Jeddah", "Makkah", ["King Abdulaziz Rd", "Tahlia St", "Palestine Rd"]), ("Dammam", "Eastern Province", ["King Fahd Rd", "Prince Mohammed Bin Fahd Rd"])], "postal_codes": ["11564", "21577", "31952"]},
    "IL": {"legal": {"jurisdiction": "Israel", "privacy_reference": "Privacy Protection Law", "cookie_reference": "Privacy Protection Law", "regulator": "Privacy Protection Authority"}, "company_suffix": "Ltd.", "phone_area_codes": ["02", "03", "04", "08", "09"], "phone_country_code": "+972", "phone_pattern": "{cc} {area}-{first}-{second}", "cities": [("Tel Aviv", "Tel Aviv", ["Dizengoff St", "Rothschild Blvd", "Ben Yehuda St"]), ("Jerusalem", "Jerusalem", ["Jaffa Rd", "Ben Yehuda St", "King George St"]), ("Haifa", "Haifa", ["Herzl St", "Hanassi Ave"])], "postal_codes": ["6100001", "9140100", "3308001"]},
    "TR": {"legal": {"jurisdiction": "Turkey", "privacy_reference": "KVKK", "cookie_reference": "KVKK", "regulator": "Personal Data Protection Authority"}, "company_suffix": "A.Ş.", "phone_area_codes": ["212", "216", "312", "232", "322"], "phone_country_code": "+90", "phone_pattern": "{cc} {area} {first} {second}", "cities": [("Istanbul", "Istanbul", ["İstiklal Ave", "Bağdat Caddesi", "Nişantaşı"]), ("Ankara", "Ankara", ["Kızılay Square", "Tunalı Hilmi Caddesi", "Atatürk Blvd"]), ("Izmir", "Izmir", ["Kordon", "Alsancak", "Konak Square"])], "postal_codes": ["34000", "06000", "35000"]},
    "BD": {"legal": {"jurisdiction": "Bangladesh", "privacy_reference": "Digital Security Act", "cookie_reference": "Digital Security Act", "regulator": "Digital Security Agency"}, "company_suffix": "Ltd.", "phone_area_codes": ["02", "031", "041", "051", "081"], "phone_country_code": "+880", "phone_pattern": "{cc} {area}-{first}{second}", "cities": [("Dhaka", "Dhaka", ["Mirpur Rd", "Dhanmondi Rd", "Gulshan Ave"]), ("Chittagong", "Chittagong", ["Agrabad", "Nasirabad", "GEC Circle"]), ("Sylhet", "Sylhet", ["Zindabazar", "Bondor Bazar"])], "postal_codes": ["1000", "4000", "3100"]},
    "KH": {"legal": {"jurisdiction": "Cambodia", "privacy_reference": "Cybersecurity Law", "cookie_reference": "Cybersecurity Law", "regulator": "Ministry of Interior"}, "company_suffix": "Co., Ltd.", "phone_area_codes": ["023", "025", "026"], "phone_country_code": "+855", "phone_pattern": "{cc} {area} {first}{second}", "cities": [("Phnom Penh", "Phnom Penh", ["Sisowath Quay", "Norodom Blvd", "Monivong Blvd"]), ("Siem Reap", "Siem Reap", ["Pub St", "Sivutha Blvd", "National Rd 6"]), ("Battambang", "Battambang", ["Street 1", "Street 2"])], "postal_codes": ["12000", "17000", "02000"]},
    # Oceania
    "NZ": {"legal": {"jurisdiction": "New Zealand", "privacy_reference": "Privacy Act 2020", "cookie_reference": "Privacy Act 2020", "regulator": "Office of the Privacy Commissioner"}, "company_suffix": "Ltd", "phone_area_codes": ["09", "04", "03", "07", "06"], "phone_country_code": "+64", "phone_pattern": "{cc} {area}-{first}-{second}", "cities": [("Auckland", "Auckland", ["Queen St", "Ponsonby Rd", "Karangahape Rd"]), ("Wellington", "Wellington", ["Lambton Quay", "Cuba St", "Willis St"]), ("Christchurch", "Canterbury", ["Oxford Terrace", "Colombo St", "Cashel St"])], "postal_codes": ["1010", "6011", "8011"]},
    # Latin America
    "MX": {"legal": {"jurisdiction": "Mexico", "privacy_reference": "LFPDPPP", "cookie_reference": "LFPDPPP", "regulator": "National Institute of Transparency"}, "company_suffix": "S.A. de C.V.", "phone_area_codes": ["55", "33", "81", "222", "664"], "phone_country_code": "+52", "phone_pattern": "{cc} {area} {first}-{second}", "cities": [("Mexico City", "CDMX", ["Reforma", "Insurgentes", "Juárez"]), ("Guadalajara", "Jalisco", ["Av. Juárez", "López Cotilla", "Av. Vallarta"]), ("Monterrey", "Nuevo León", ["Av. Constitución", "Morelos", "Av. Garza Sada"])], "postal_codes": ["06600", "44100", "64000"]},
    "BR": {"legal": {"jurisdiction": "Brazil", "privacy_reference": "LGPD", "cookie_reference": "LGPD", "regulator": "National Data Protection Authority"}, "company_suffix": "Ltda.", "phone_area_codes": ["11", "21", "31", "41", "51"], "phone_country_code": "+55", "phone_pattern": "{cc} ({area}) {first}-{second}", "cities": [("São Paulo", "SP", ["Paulista Ave", "Oscar Freire St", "Augusta St"]), ("Rio de Janeiro", "RJ", ["Copacabana", "Ipanema", "Leblon"]), ("Brasília", "DF", ["Esplanada dos Ministérios", "W3 North"])], "postal_codes": ["01310-100", "20040-020", "70040-010"]},
    "AR": {"legal": {"jurisdiction": "Argentina", "privacy_reference": "Personal Data Protection Law", "cookie_reference": "Personal Data Protection Law", "regulator": "Agency of Access to Public Information"}, "company_suffix": "S.A.", "phone_area_codes": ["011", "0351", "0261", "0341", "0223"], "phone_country_code": "+54", "phone_pattern": "{cc} {area} {first}-{second}", "cities": [("Buenos Aires", "Buenos Aires", ["Florida St", "Corrientes Ave", "Santa Fe Ave"]), ("Córdoba", "Córdoba", ["General Paz Ave", "Colón Blvd", "27 de Abril"]), ("Rosario", "Santa Fe", ["Córdoba Ave", "San Martín St", "Corrientes St"])], "postal_codes": ["C1000", "X5000", "S2000"]},
    "CO": {"legal": {"jurisdiction": "Colombia", "privacy_reference": "Law 1581", "cookie_reference": "Law 1581", "regulator": "Superintendency of Industry and Commerce"}, "company_suffix": "S.A.S.", "phone_area_codes": ["601", "604", "605", "606", "608"], "phone_country_code": "+57", "phone_pattern": "{cc} {area} {first}{second}", "cities": [("Bogotá", "Bogotá", ["Carrera 7", "Carrera 15", "Zona Rosa"]), ("Medellín", "Antioquia", ["El Poblado Ave", "Carrera 70", "Junín St"]), ("Cali", "Valle del Cauca", ["Av. Roosevelt", "Av. 6N", "Calle 5"])], "postal_codes": ["110111", "050001", "760001"]},
    "CL": {"legal": {"jurisdiction": "Chile", "privacy_reference": "Law 19628", "cookie_reference": "Law 19628", "regulator": "Council for Transparency"}, "company_suffix": "SpA", "phone_area_codes": ["2", "32", "33", "34", "41"], "phone_country_code": "+56", "phone_pattern": "{cc} {area} {first}{second}", "cities": [("Santiago", "RM", ["Alameda", "Providencia Ave", "Paseo Ahumada"]), ("Valparaíso", "Valparaíso", ["Avenida Argentina", "Pedro Montt Ave"]), ("Concepción", "Biobío", ["Avenida O'Higgins", "Barros Arana St"])], "postal_codes": ["8320000", "2360000", "4030000"]},
    "PE": {"legal": {"jurisdiction": "Peru", "privacy_reference": "Law 29733", "cookie_reference": "Law 29733", "regulator": "National Authority for the Protection of Personal Data"}, "company_suffix": "S.A.C.", "phone_area_codes": ["01", "054", "074", "044", "084"], "phone_country_code": "+51", "phone_pattern": "{cc} {area} {first}{second}", "cities": [("Lima", "Lima", ["Larco Ave", "Benavides Ave", "Jirón de la Unión"]), ("Arequipa", "Arequipa", ["Mercaderes St", "Santa Catalina St"]), ("Cusco", "Cusco", ["Avenida El Sol", "Plaza de Armas"])], "postal_codes": ["15001", "04001", "08001"]},
    "VE": {"legal": {"jurisdiction": "Venezuela", "privacy_reference": "Constitutional Law", "cookie_reference": "Constitutional Law", "regulator": "Ministry of Science and Technology"}, "company_suffix": "C.A.", "phone_area_codes": ["0212", "0261", "0241", "0251", "0243"], "phone_country_code": "+58", "phone_pattern": "{cc} {area} {first}{second}", "cities": [("Caracas", "Capital District", ["Sabana Grande Blvd", "Bello Campo", "Chacaíto"]), ("Maracaibo", "Zulia", ["Calle 77", "Av. El Milagro"]), ("Valencia", "Carabobo", ["Av. Díaz Moreno", "Calle Colombia"])], "postal_codes": ["1010", "4001", "2001"]},
    "EC": {"legal": {"jurisdiction": "Ecuador", "privacy_reference": "Organic Law on Personal Data Protection", "cookie_reference": "Organic Law on Personal Data Protection", "regulator": "Superintendency of Companies"}, "company_suffix": "S.A.", "phone_area_codes": ["02", "04", "07", "03", "06"], "phone_country_code": "+593", "phone_pattern": "{cc} {area} {first}{second}", "cities": [("Quito", "Pichincha", ["Amazonas Ave", "Colón St", "Naciones Unidas Ave"]), ("Guayaquil", "Guayas", ["Malecón 2000", "9 de Octubre Ave", "Av. Francisco de Orellana"]), ("Cuenca", "Azuay", ["Gran Colombia Ave", "Benigno Malo Ave"])], "postal_codes": ["170401", "090101", "010101"]},
    "BO": {"legal": {"jurisdiction": "Bolivia", "privacy_reference": "Law No. 164", "cookie_reference": "Law No. 164", "regulator": "Ministry of Works and Services"}, "company_suffix": "S.R.L.", "phone_area_codes": ["02", "03", "04"], "phone_country_code": "+591", "phone_pattern": "{cc} {area}-{first}{second}", "cities": [("La Paz", "La Paz", ["Prado Ave", "16 de Julio Ave", "Camacho Ave"]), ("Santa Cruz", "Santa Cruz", ["Calle Junín", "Av. Roca y Coronado", "Monseñor Rivero St"]), ("Cochabamba", "Cochabamba", ["Avenida Heroínas", "Av. Ballivián"])], "postal_codes": ["0000", "0001", "0002"]},
    "PY": {"legal": {"jurisdiction": "Paraguay", "privacy_reference": "Law 1682", "cookie_reference": "Law 1682", "regulator": "National Secretariat of Information and Communication Technologies"}, "company_suffix": "S.A.", "phone_area_codes": ["021", "0981", "061", "071"], "phone_country_code": "+595", "phone_pattern": "{cc} {area} {first}{second}", "cities": [("Asunción", "Asunción", ["Palma St", "España Ave", "Mcal. López Ave"]), ("Ciudad del Este", "Alto Paraná", ["Avenida San Blas", "Adrian Jara St"]), ("Encarnación", "Itapúa", ["Mariscal Estigarribia Ave", "Carlos Antonio López St"])], "postal_codes": ["1001", "7000", "6500"]},
    "UY": {"legal": {"jurisdiction": "Uruguay", "privacy_reference": "Law 18331", "cookie_reference": "Law 18331", "regulator": "Data Regulatory Unit"}, "company_suffix": "S.A.", "phone_area_codes": ["02", "032", "052", "042", "072"], "phone_country_code": "+598", "phone_pattern": "{cc} {area} {first}-{second}", "cities": [("Montevideo", "Montevideo", ["18 de Julio Ave", "Peatonal Sarandí", "Av. Brasil"]), ("Salto", "Salto", ["Uruguay St", "Artigas Blvd"]), ("Punta del Este", "Maldonado", ["Gorlero Ave", "Av. Roosevelt"])], "postal_codes": ["11100", "50000", "20100"]},
    "CR": {"legal": {"jurisdiction": "Costa Rica", "privacy_reference": "Law 8968", "cookie_reference": "Law 8968", "regulator": "Agency for the Protection of the Inhabitants' Data"}, "company_suffix": "S.A.", "phone_area_codes": ["2", "4", "6", "7", "8"], "phone_country_code": "+506", "phone_pattern": "{cc} {first}-{second}", "cities": [("San José", "San José", ["Paseo Colón", "Avenida Central", "Calle 4"]), ("Liberia", "Guanacaste", ["Calle Real", "Ave Central"]), ("Alajuela", "Alajuela", ["Calle 1", "Calle 2"])], "postal_codes": ["10101", "50101", "20101"]},
    "PA": {"legal": {"jurisdiction": "Panama", "privacy_reference": "Law 81", "cookie_reference": "Law 81", "regulator": "National Authority for Transparency and Access to Information"}, "company_suffix": "S.A.", "phone_area_codes": ["2", "3", "4", "6", "7"], "phone_country_code": "+507", "phone_pattern": "{cc} {first}-{second}", "cities": [("Panama City", "Panamá", ["Via España", "Calle 50", "Av. Balboa"]), ("Colón", "Colón", ["Calle 11", "Av. del Frente"]), ("David", "Chiriquí", ["Avenida Obaldia", "Calle Central"])], "postal_codes": ["0801", "0302", "0401"]},
    "GT": {"legal": {"jurisdiction": "Guatemala", "privacy_reference": "Decree 13-2018", "cookie_reference": "Decree 13-2018", "regulator": "Ministry of Justice"}, "company_suffix": "S.A.", "phone_area_codes": ["2", "3", "4", "5", "6"], "phone_country_code": "+502", "phone_pattern": "{cc} {first}-{second}", "cities": [("Guatemala City", "Guatemala", ["6ta Avenida", "Avenida Reforma", "Blvd. Los Próceres"]), ("Quetzaltenango", "Quetzaltenango", ["4a Calle", "7a Av."]), ("Antigua", "Sacatepéquez", ["5a Ave Norte", "Calle del Arco"])], "postal_codes": ["01001", "09001", "03001"]},
    "DO": {"legal": {"jurisdiction": "Dominican Republic", "privacy_reference": "Law 172-13", "cookie_reference": "Law 172-13", "regulator": "Attorney General's Office"}, "company_suffix": "S.A.", "phone_area_codes": ["809", "829", "849"], "phone_country_code": "+1", "phone_pattern": "{cc} ({area}) {first}-{second}", "cities": [("Santo Domingo", "Distrito Nacional", ["Avenida Abraham Lincoln", "Avenida 27 de Febrero", "Av. Winston Churchill"]), ("Santiago de los Caballeros", "Santiago", ["Avenida Las Carreras", "Av. Juan Pablo Duarte"]), ("La Romana", "La Romana", ["Calle Padre Ayala"])], "postal_codes": ["10101", "51000", "22000"]},
}
THEME_ORDER = ['cleaning', 'marketing_agency', 'cafe_restaurant', 'fitness_club', 'news', 'apparel']
LANGUAGE_ORDER = ['en', 'de', 'es', 'fr', 'it']
GEO_ORDER = [
    # North America
    'US', 'CA', 'MX',
    # Europe
    'UK', 'DE', 'FR', 'ES', 'IT', 'AT', 'BE', 'BG', 'CH', 'CY', 'CZ',
    'DK', 'EE', 'FI', 'GR', 'HR', 'HU', 'IE', 'LT', 'LU', 'LV', 'MT',
    'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK', 'UA',
    # Asia
    'SG', 'JP', 'CN', 'KR', 'IN', 'TH', 'ID', 'MY', 'PH', 'VN', 'TW',
    'HK', 'AE', 'SA', 'IL', 'TR', 'BD', 'KH',
    # Oceania
    'AU', 'NZ',
    # Latin America
    'BR', 'AR', 'CO', 'CL', 'PE', 'VE', 'EC', 'BO', 'PY', 'UY',
    'CR', 'PA', 'GT', 'DO',
]
PAGE_TITLES = {
    "en": {
        "index": "Home",
        "about": "About",
        "services": "Services",
        "offerings": "Offerings",
        "portfolio": "Portfolio",
        "projects": "Projects",
        "contact": "Contact",
    },
    "de": {
        "index": "Startseite",
        "about": "Über uns",
        "services": "Dienstleistungen",
        "offerings": "Angebote",
        "portfolio": "Portfolio",
        "projects": "Projekte",
        "contact": "Kontakt",
    },
    "es": {
        "index": "Inicio",
        "about": "Acerca de",
        "services": "Servicios",
        "offerings": "Ofertas",
        "portfolio": "Portafolio",
        "projects": "Proyectos",
        "contact": "Contacto",
    },
    "fr": {
        "index": "Accueil",
        "about": "À propos",
        "services": "Services",
        "offerings": "Offres",
        "portfolio": "Portefeuille",
        "projects": "Projets",
        "contact": "Contact",
    },
    "it": {
        "index": "Home",
        "about": "Chi siamo",
        "services": "Servizi",
        "offerings": "Offerte",
        "portfolio": "Portfolio",
        "projects": "Progetti",
        "contact": "Contatto",
    },
}
